use db;
CREATE TABLE Ehesn (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'o2KxGg0bB', 'MSS4');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'HqnGfpCMqBFvsYowv8x7CZ', 'k1pjS9Nr');
SELECT * FROM example  WHERE id=19;
SELECT * FROM example  WHERE id=20;
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'RhJ11dePUSjDoIdYsRMI', 'wq9uqh8x9qENHU7Ta9D7MIEUwhTZw');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'HMQNWKF8618QkSEEnKVwXF21', 'Cn');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'aq49HWDq9ODG0edE3zJxFk2z9nG7', 'IDnVUF66FXTkp3gMw83ilCfNcAB');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'Ui0', 'rp4V2Hpq6');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'AXb', 'ukxwA2dO2YRPDEG57Xa');
SELECT * FROM example  WHERE id=20;
SELECT * FROM example  WHERE name="oppo";
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'JgkHxMj8sk8ze4q31EhrU3Z9W9Q6B', '4YkLDtNkR3pAif86AWHvgJCa2');
SELECT * FROM example  WHERE name="test";
INSERT INTO Ehesn (id,name,pwd) VALUES (null, '4R2dODrolCeB', '8KQ54XHU');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'UdlY1', 'xgIO');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'DV5XAUgH4', '49uWpzfR611U');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'fYjpQk5kAyUK72uH107DVG4Qq6gnn', '');
SELECT * FROM example  WHERE name="UKuS";
INSERT INTO Ehesn (id,name,pwd) VALUES (null, '7d7dcTjMboYa4t69VdG', 'wgTW9x5aXNMyVMzCjVlLaI');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, '0bd7t5fZ91OUbor', 'P2NI');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, '2gcozc9PFGEAe2BpWdqNRYDh8', 'tKKdw6Js49pX8qrVLVosgcl');
INSERT INTO Ehesn (id,name,pwd) VALUES (null, 'j84wEiAgDCWtfJnH5oN9HegdG', 'omvdh2Y24DsSqO2O');
SELECT * FROM Ehesn  WHERE id=6;
SELECT * FROM Ehesn  WHERE name="d";
SELECT * FROM Ehesn  WHERE name="OJP";
SELECT * FROM Ehesn;
SELECT * FROM Ehesn  WHERE name="fgCi98grylDoV2xKzZkU";
SELECT * FROM Ehesn  WHERE name="D2NY";
SELECT * FROM Ehesn  WHERE id=7;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
