use db;
CREATE TABLE tvpFm (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'nm6pH2UVzarO5AzDTeWLlVofAxO', 'loAhcyfyV');
SELECT * FROM example  WHERE id=13;
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'sWvrcb9SwE', 'gvvymA8SRbdLj0DnUMoCyEHq');
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'WPl51qX8jVy', 'a1Y');
SELECT * FROM example  WHERE name="neglecthim";
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'RTaEo', 'hlll8mWgiFkRAr');
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'npvQ1GZfhkMxXChKaMyCa2dk', 'B5fjHCoPLNkcIR');
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'TIY', 'jJKrjdkB1dM3qXu8BVj0xBFh9tv');
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'Db3LwRCxIBY26FNCmRziGw7buT3', 'c');
INSERT INTO tvpFm (id,name,pwd) VALUES (null, '25D6YJTumrikCsDGBUICpYB9QW4', 'f8YDluuGozR7eb7EuwbrKmqifD1Z');
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'l2RGyP', 'i6');
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'eZ4x2FCg2ovPp0', 'OxNKmeoO3');
SELECT * FROM tvpFm;
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'fHpuFNuPwpQtc0sAuGNlLNEP', 'DfwVwdhP0LRRBnO2KYnCJk68tc8r7');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO tvpFm (id,name,pwd) VALUES (null, '3hQcNEDvQbxGKtlaM7', 'b9J893VpHN');
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'WQkebjKkp9eOgMvArHQk201', 'Sc7RXpXMUFPUuHJwJTPNpafHiO8w');
SELECT * FROM example  WHERE name="nclgqDGdAVsml83O1hwAIej2Avfv";
SELECT * FROM example  WHERE name="LQbIwg";
SELECT * FROM example  WHERE id=4;
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 't', '5CRA6OpGid4vGVH');
SELECT * FROM example  WHERE id=19;
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'UTuW', '5vgGqeQgSg2QFhf');
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'URjMx6TpBCWuKGFBSGkXn0fdFuKT', '3AqIoa5gIpW');
SELECT * FROM example  WHERE id=8;
INSERT INTO tvpFm (id,name,pwd) VALUES (null, 'lRVrNm', 'FMMdDgaKjpba6dHPBLdJx');
SELECT * FROM tvpFm  WHERE name="fUiRA63kljQO";
SELECT * FROM tvpFm  WHERE id=4;
SELECT * FROM tvpFm  WHERE id=17;
SELECT * FROM tvpFm  WHERE id=2;
SELECT * FROM tvpFm  WHERE name="ZwqX57h73X50AvyiXAlt2yvXzUMf";
SELECT * FROM tvpFm  WHERE name="5eJj66Zr0Rvh2rT2B8";
