use db;
CREATE TABLE vuJyY (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="";
SELECT * FROM example  WHERE id=19;
INSERT INTO vuJyY (id,name,pwd) VALUES (null, 'wkPDGiUg2sQuZhllIbHX92V61PuaW', 'gjvVnKvxXQPAVyPEOG6');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, 'EOZhnV8AFk', 'GCJ9');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, 'arCZv6ec2vfgsAw', 'NhI7M');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, 'uA', 'iDRCsZs8DFso');
SELECT * FROM example  WHERE name="hello";
INSERT INTO vuJyY (id,name,pwd) VALUES (null, '8WbyJi8YWasxlqypKkzWdfTqBK', 'qsdttTKSwXvKYKcMwoXYMXvPdv');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, 'CzxqIl4iXzWK', 'V3aYAzom2NDle0Xd7hAk9ZlMg');
SELECT * FROM example  WHERE id=9;
INSERT INTO vuJyY (id,name,pwd) VALUES (null, 'YSxOwGXOuUjt1CLfWMPWAF7Nt9', 'WYNpo');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, 'Zz3U78QNEvb4IBDKF', 'oj');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, 'rmbbmw', 'TPh');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, 'awRIOdEXS2N4umVlW3ZSscj8CP', '1Lq7JNkc1v8V96pl4');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, '5', 'B1rhv5gVMXdd6xme93spoTUbnC');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, '3nwrwSJnTQWHmkqyCoRd', 'jfWC8zuyuPs5vEtenK7K');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, '9xmPzynacSaNqS', 'F9FH7r');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, '5ncZTaZtnTk', 'ILT4RZeywpOXhAfLEUT');
INSERT INTO vuJyY (id,name,pwd) VALUES (null, 'L', 'mlSiSZzSJvsk5oyiA');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM vuJyY  WHERE name="Gsi";
SELECT * FROM vuJyY;
SELECT * FROM vuJyY  WHERE name="LTUuWWcmYTqibz";
SELECT * FROM vuJyY  WHERE name="oWtHFm";
