use db;
CREATE TABLE CyBpb (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'jYBoWcFNSR', 'kIarquUPBSg8JEgeFIyg77B');
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'KjGg', 'fY3sHUTbfEvQ8Mj5xw5UavLj');
SELECT * FROM example  WHERE name="jqqRW630cHklSwyIPH";
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'UGrGHGNq7ejE9CUdZP8pxv2iyy75', 'qsIKey');
SELECT * FROM example  WHERE id=3;
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'F1gKNVWkV4aH2Mi5yAJKIdDDe', 'lPgqaF');
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'PfgsjH1GnNBVcWRyXd7qfDTACihY', 'dTMKLbe9dH');
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'g6OBQsIhnRQQJwUr71Bwb3P', 'Sd7dj98wFcmKfS0Z');
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'YZgZgvWJ76n3kj6uNE9tjTsY4n', 'D8nbTPLpFHUhQ4BSZ82knslf42P4i');
SELECT * FROM example  WHERE name="TMyW33QHhLoU";
SELECT * FROM example  WHERE name="Bp2nJwKnH4MpoqSch5i27";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO CyBpb (id,name,pwd) VALUES (null, '', 'eosXLIvta');
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'dQN', 'zEQWl');
INSERT INTO CyBpb (id,name,pwd) VALUES (null, '2YoGqJhma5BK', '5nL5OcjEhgjWDeQoAQM0xjW');
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'lTPWJKKAjxNNlJ28Zzw7g9Wn1', '7nSi2n1jrJDhYb');
SELECT * FROM example  WHERE name="aCpJb3MmufLILL6";
SELECT * FROM CyBpb;
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'eWzabM9XxS3ZO', '8zdevPYMHMa');
INSERT INTO CyBpb (id,name,pwd) VALUES (null, '1KNXu2Y1mqIvMObsSQOzSK', 'tPkyMe1Jsy1RAx7NxUw9QYN');
INSERT INTO CyBpb (id,name,pwd) VALUES (null, '620WRMMSiNxS4lM1gyquEahBj', 'ASpqly3omoMVmC9');
INSERT INTO CyBpb (id,name,pwd) VALUES (null, 'UCtNGRiirskPeHyS0vS', 'w8VKXNbeSJHHtwNo1fYH6NKHL1Z');
SELECT * FROM CyBpb  WHERE name="VUcwCmbF";
SELECT * FROM CyBpb  WHERE name="pwQxQMeBUV9tL";
SELECT * FROM CyBpb  WHERE id=13;
