use db;
CREATE TABLE Uxfmh (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO Uxfmh (id,name,pwd) VALUES (null, 'Vx9vGb2WsNSJz0gL8mwVzJdl', '5FwoyJnvX8fvJsS7jj4bvk');
SELECT * FROM example  WHERE name="ogEaIXaQeR716zRl";
SELECT * FROM example  WHERE name="bgrYqKg8b5vr6PzbHmf";
INSERT INTO Uxfmh (id,name,pwd) VALUES (null, 'yjFwNsfQBd9yoPtPfVgWOTul0mu', '1');
INSERT INTO Uxfmh (id,name,pwd) VALUES (null, 'sAFG2GY0Lg6WdyTAEcMumR0Hw', 'eERkzcwIcq2nIEAA4hJ');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE name="2a8sEujrpq9jXU";
SELECT * FROM example  WHERE name="xmRib5JuyuLGwjoVLjCMuv2X3";
SELECT * FROM Uxfmh;
SELECT * FROM Uxfmh  WHERE name="p3rl5";
SELECT * FROM Uxfmh  WHERE name="6eJXeM7YZjyv4KIkq";
SELECT * FROM Uxfmh  WHERE id=3;
SELECT * FROM Uxfmh  WHERE id=3;
SELECT * FROM Uxfmh  WHERE id=3;
SELECT * FROM Uxfmh  WHERE id=0;
SELECT * FROM Uxfmh  WHERE name="IK9lSY1HSIiQpcRE0ngLKP4Acmt";
SELECT * FROM Uxfmh  WHERE name="humqcUyt7q4FR2e06AoHdvq";
