use db;
CREATE TABLE ycUZc (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE id=19;
SELECT * FROM example  WHERE name="xrayfighter";
SELECT * FROM example  WHERE id=15;
INSERT INTO ycUZc (id,name,pwd) VALUES (null, 'ySPj7Yge8ANTkX9Sj', 'TujM1CGZsi9');
SELECT * FROM example  WHERE name="zookeeper001";
SELECT * FROM example  WHERE name="cici1001";
SELECT * FROM example  WHERE name="pinchen";
SELECT * FROM example  WHERE name="Sct3dDuke07LBJ";
INSERT INTO ycUZc (id,name,pwd) VALUES (null, '0BQwkns5jIQCTw', 'XQIz6U9QW');
SELECT * FROM ycUZc;
SELECT * FROM example  WHERE id=14;
SELECT * FROM ycUZc  WHERE id=2;
SELECT * FROM ycUZc  WHERE name="DYSHMDx";
SELECT * FROM ycUZc  WHERE name="9Sj8wCTfw";
SELECT * FROM ycUZc  WHERE name="";
SELECT * FROM ycUZc  WHERE id=1;
