use db;
CREATE TABLE TOupe (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO TOupe (id,name,pwd) VALUES (null, 'KfPjjXKaDw', 'GOkSJ');
INSERT INTO TOupe (id,name,pwd) VALUES (null, 'f7ybzCPFrN39IIlpNzXJ4wd5O9OEI', '');
INSERT INTO TOupe (id,name,pwd) VALUES (null, 'OI5BiAGb', 'NuXBhwhH4nJABxuxP');
INSERT INTO TOupe (id,name,pwd) VALUES (null, 'XDZmz', 'Dce');
SELECT * FROM TOupe;
SELECT * FROM example  WHERE name="cinkrE5lTVbt4RFnhnRXOX92Tj";
SELECT * FROM example  WHERE id=9;
SELECT * FROM example  WHERE name="VaATE9OCijmXTPNuHWA19DmheQ";
SELECT * FROM example  WHERE name="Vw0GR";
SELECT * FROM example  WHERE id=7;
SELECT * FROM example  WHERE name="lemonpie";
INSERT INTO TOupe (id,name,pwd) VALUES (null, 'n8wfEe4LicMnEH2XNG5NYZ', '');
SELECT * FROM example  WHERE name="faker";
INSERT INTO TOupe (id,name,pwd) VALUES (null, '7VF74U4EB7uCLuFGc5', 'Urg3zJ');
SELECT * FROM example  WHERE name="Qt0SB76yxoZUZEiaMhZM";
INSERT INTO TOupe (id,name,pwd) VALUES (null, 'YYZMBzldgwLn2uZ51hqyGT', 'oM90DTjk3alnY');
INSERT INTO TOupe (id,name,pwd) VALUES (null, 'vd', 'mpNntA5TAHJ5oO5myHPQWdsX');
INSERT INTO TOupe (id,name,pwd) VALUES (null, 'PRD1WhtRffbKa6dDFi3EEAJ', 'MmZTwRnLTHKNxrIVCHTaQG');
INSERT INTO TOupe (id,name,pwd) VALUES (null, 'VDMeMT', '3mI2Ces9qQFAbB4');
INSERT INTO TOupe (id,name,pwd) VALUES (null, 'mj3j1', 'F13');
SELECT * FROM example  WHERE name="rightnow2019";
SELECT * FROM TOupe  WHERE name="UdadsDph7yP";
SELECT * FROM TOupe  WHERE id=10;
SELECT * FROM TOupe  WHERE name="kbd69r4muDtCIIuhJmy4rxsTKRqW";
SELECT * FROM TOupe  WHERE id=4;
SELECT * FROM TOupe  WHERE name="Qx9mooIa4E0c2xxivEys4ePiRf";
