use db;
CREATE TABLE UPvsU (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO UPvsU (id,name,pwd) VALUES (null, 'jRfhIv6W7CG3k6qH2t', 'tQTXXVZ5PCCYvBf6K70OO');
SELECT * FROM example  WHERE name="K1ga";
SELECT * FROM example  WHERE name="E";
INSERT INTO UPvsU (id,name,pwd) VALUES (null, 'TxFas', 'A4nQcSLKg9rqeo7zbGmbJc3');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, 'CO9grLWqorMKfeLeCkLGN7uv2O', 'WOB1QZgn');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, '9T9', 'Eq2dAb3otepMyKBWpSTTE5Tpu');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, 'Zuh92Oe6iat', 'pmL8EZJFWCDGlB0HsF8rH5YdjKjA7');
SELECT * FROM example  WHERE name="6Zb6TMq";
INSERT INTO UPvsU (id,name,pwd) VALUES (null, 'rt1sg2xk6AZhQaM6H4x', 'VuiDoQaghr9lp');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, '', '3PcZVHmoAcmvNmdb7Jd');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, 'R2zOdKLieH', 'Dpr4sjdvP53e26mHE6Fo8Li7dbB');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, '3hk4Oe00dCs5Ts', '4iwjUcSNDAUIe1yombydO');
SELECT * FROM example  WHERE name="euro";
SELECT * FROM example  WHERE name="GeSXc0hMAAFHjsxtNWRN6BynYh";
INSERT INTO UPvsU (id,name,pwd) VALUES (null, '', 'enpSHLkEr2Ne');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, '58fBe', '');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, 'f6HNpPCdB60UyxveIm', '');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, '0UkPYErMwVIZRjwpmpteMO7dEwR', 'H2HB5SG3pB2v28hoAN');
SELECT * FROM example  WHERE name="mcdonalds";
SELECT * FROM example  WHERE name="restinpeace";
INSERT INTO UPvsU (id,name,pwd) VALUES (null, '0', 'iQsnAk9DCBgKfvDNC');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, 'gZKmRHhhYHhccGXuMOOWm2W4', 'LI4CYkhNHZRGH6LWzULRcDFX20');
INSERT INTO UPvsU (id,name,pwd) VALUES (null, 'aTgDWm4SyDOTt17KHUbas5TmAy6y', 'AYj7XOrlTESImCm9WEMu5');
SELECT * FROM example  WHERE name="rightnow2019";
INSERT INTO UPvsU (id,name,pwd) VALUES (null, '', 'UTz4nN2nQUWSQ0SClzAJxCLqYIV0C');
SELECT * FROM UPvsU  WHERE id=0;
SELECT * FROM UPvsU;
SELECT * FROM UPvsU  WHERE name="jUp";
SELECT * FROM UPvsU  WHERE name="veTbKNNsYHY8mRnP";
SELECT * FROM UPvsU  WHERE name="";
SELECT * FROM UPvsU  WHERE id=15;
SELECT * FROM UPvsU  WHERE id=10;
SELECT * FROM UPvsU  WHERE name="qjimSCWHSEwMXkL";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
