use db;
CREATE TABLE CrOYH (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO CrOYH (id,name,pwd) VALUES (null, '', 'v91D8a4lRBXBtqY5OUR');
INSERT INTO CrOYH (id,name,pwd) VALUES (null, '9dFObJmuHYDRp5HVIA0', 'rUL');
SELECT * FROM example  WHERE name="killerleon";
INSERT INTO CrOYH (id,name,pwd) VALUES (null, 'HpI8t1kdm', 'LVoXjPjlZAfSW');
SELECT * FROM example  WHERE name="queue";
SELECT * FROM example  WHERE name="wGqBo4tw";
INSERT INTO CrOYH (id,name,pwd) VALUES (null, 'FtncxDKRAdtmBJ2KviLLU8Eu', 'qTBK4Exj6NChorVMbzoKWea5');
INSERT INTO CrOYH (id,name,pwd) VALUES (null, 'hvhS8Xol5', 'yBE');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO CrOYH (id,name,pwd) VALUES (null, '4QtUa0TJ42TKeI8pJFoz7iqJ5lV', 'p52vd0Lb7bZQXUHn1cMoI7TcDWYSi');
SELECT * FROM example  WHERE id=3;
INSERT INTO CrOYH (id,name,pwd) VALUES (null, 'TeglFXRQVSmHAUH', 'itCfy7rDIO');
SELECT * FROM example  WHERE id=16;
SELECT * FROM example  WHERE name="cathy3333";
INSERT INTO CrOYH (id,name,pwd) VALUES (null, 'fSVLTZhvbIpx0iZmk', 'IXq8TNjlGiSndYvGGXMjZliDE7uU');
INSERT INTO CrOYH (id,name,pwd) VALUES (null, '2UPgsgsRHyEpI14nFYN0s', '5awHXluuwmnrqAstNBCVuqgyeUkS');
INSERT INTO CrOYH (id,name,pwd) VALUES (null, 'R4nPch4sVahBa17k86A5', 'LBgalEZT73s9');
SELECT * FROM example  WHERE id=8;
SELECT * FROM CrOYH;
INSERT INTO CrOYH (id,name,pwd) VALUES (null, '2hCjFq9DcmN', 'LkBJXCqG4');
SELECT * FROM CrOYH  WHERE name="O3sl";
