use db;
CREATE TABLE pgiHv (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM pgiHv;
SELECT * FROM example  WHERE id=6;
SELECT * FROM example  WHERE name="lemonpie";
SELECT * FROM example  WHERE id=6;
SELECT * FROM example  WHERE name="Dr.Umphress";
SELECT * FROM example  WHERE name="bkAM4uJ3XEV7p5YG5iVBOdT7vuHQ1";
SELECT * FROM example  WHERE name="apple1998";
SELECT * FROM example  WHERE name="WfG";
SELECT * FROM example  WHERE name="rn";
SELECT * FROM example  WHERE name="OTXVLuAyLosXkf3U";
