use db;
CREATE TABLE aMvON (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO aMvON (id,name,pwd) VALUES (null, 'SAH88DcCE1d5vUrnrG', 'T0xDcC3BthkiU6q3itLbQQvP1Y');
INSERT INTO aMvON (id,name,pwd) VALUES (null, 'K0Cp74r', 'Mu');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE id=5;
INSERT INTO aMvON (id,name,pwd) VALUES (null, 'zxob3A21InR5h', 'sq7VSbBrASShaO7cACUNcY3');
SELECT * FROM example  WHERE name="pinchen";
SELECT * FROM aMvON;
SELECT * FROM example  WHERE name="letsparty";
SELECT * FROM example  WHERE id=20;
INSERT INTO aMvON (id,name,pwd) VALUES (null, 'qNgZOVUNN', '');
INSERT INTO aMvON (id,name,pwd) VALUES (null, '9I5WyoQ72lziJ1Qlo3ZgOnnn0Qb', '4OCmwZ1MKYy956FvxvH');
SELECT * FROM example  WHERE id=7;
SELECT * FROM example  WHERE id=3;
INSERT INTO aMvON (id,name,pwd) VALUES (null, 'Djv7EGWC8EQlBG1FsWYRObQ20BYC', 'Ya4GX88sh5V6VfgMFludd');
SELECT * FROM aMvON  WHERE id=1;
SELECT * FROM aMvON  WHERE id=1;
SELECT * FROM aMvON  WHERE name="Sn5HxrX2r3dvdYB7E2T0I";
SELECT * FROM aMvON  WHERE name="S2cpEaqs8BhnEgA";
