use db;
CREATE TABLE pnUOR (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO pnUOR (id,name,pwd) VALUES (null, 'CVquCooaVO', 'cz0lGLZee7B');
INSERT INTO pnUOR (id,name,pwd) VALUES (null, 'PlBYIrLfio1NxInyPoKq7sA9Adj', 'xCoCV8Xnay2r9RkmIgmoBmpf');
SELECT * FROM example  WHERE name="cathy3333";
SELECT * FROM example  WHERE name="yougurttastesgood";
SELECT * FROM example  WHERE name="MfAKkuOTJMg";
INSERT INTO pnUOR (id,name,pwd) VALUES (null, '7ZXssdLvneY8MfwB3', '4OswxdzKAs8fmvJ4YjubalyS');
INSERT INTO pnUOR (id,name,pwd) VALUES (null, 'nXH', 'Z2FDTE8LPvVu44G');
INSERT INTO pnUOR (id,name,pwd) VALUES (null, 'WGgp6FqeuiG9NSuOrFUxWlZ', 'G5GE7IypidVP8gCrYLuG5o7');
SELECT * FROM example  WHERE name="YHhyVity5i4qyb17VDe";
SELECT * FROM example  WHERE name="italy1912";
INSERT INTO pnUOR (id,name,pwd) VALUES (null, 'J2I7hQTOdL23PQ8UOLp2XI516', 'HTKlb62XSrW');
INSERT INTO pnUOR (id,name,pwd) VALUES (null, 'zR0', 'q1GJ6L1IGR6llvuW3T');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE name="PREUOOV10LPtFp9VIZmjZh";
INSERT INTO pnUOR (id,name,pwd) VALUES (null, '9MM9HkLXV4aUChbF', 'qqIF92DdBJ3gzW2yIMYD2');
INSERT INTO pnUOR (id,name,pwd) VALUES (null, 'YwkGK34EM0vErJjMJMKU', 'Dw1Gzo1HiW14uiLL5zbRMC8XKV');
SELECT * FROM example  WHERE name="kdimentions";
SELECT * FROM pnUOR;
SELECT * FROM example  WHERE name="pyazVIW25GkIp37Btbd3hoYU";
INSERT INTO pnUOR (id,name,pwd) VALUES (null, 'EkOE', 'TgdCLolyzYAsMQ9jXJ');
INSERT INTO pnUOR (id,name,pwd) VALUES (null, 'NYwoA3UwWJAtUhpAz', 'mSd36u97rwfbtOWMCTuaK');
INSERT INTO pnUOR (id,name,pwd) VALUES (null, 'tR2U5NFeVu94tT', 'imR8EkF4dgjlnpuR8pnRngSeFyj9I');
INSERT INTO pnUOR (id,name,pwd) VALUES (null, '', 'Vb27FOuzdFFCQVpMfmdqHT');
SELECT * FROM pnUOR  WHERE name="";
SELECT * FROM pnUOR  WHERE id=3;
SELECT * FROM pnUOR  WHERE id=10;
SELECT * FROM pnUOR  WHERE name="DWBLqT6OtjgjQj";
SELECT * FROM pnUOR  WHERE id=4;
