use db;
CREATE TABLE MNeKo (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE id=16;
SELECT * FROM example  WHERE name="xeoncpu";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE name="xrayfighter";
SELECT * FROM example  WHERE name="xrayfighter";
SELECT * FROM example  WHERE name="lemonpie";
SELECT * FROM MNeKo;
SELECT * FROM example  WHERE id=11;
SELECT * FROM example  WHERE id=5;
INSERT INTO MNeKo (id,name,pwd) VALUES (null, 'PgvbjpMsGr4dMvWWedobc', 'HwNU6QUvAzOCPSt6UOvc1G4pFSKe');
SELECT * FROM example  WHERE name="yHkAoNqUw7XNYDYpX";
SELECT * FROM MNeKo  WHERE id=1;
SELECT * FROM MNeKo  WHERE id=1;
SELECT * FROM MNeKo  WHERE name="6dHYrilDBFCbsymEH1bk98QKbZ";
SELECT * FROM MNeKo  WHERE name="dvrCTElQz9zwwmYoiEd8AceX9Gs";
SELECT * FROM MNeKo  WHERE id=1;
SELECT * FROM MNeKo  WHERE name="Bg";
SELECT * FROM MNeKo  WHERE id=1;
SELECT * FROM MNeKo  WHERE name="Xgg1vRhs1ei6OKieJO";
