use db;
CREATE TABLE wRykn (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO wRykn (id,name,pwd) VALUES (null, '9hpqvhZbmWozUlKRsOUMWJwmm', '');
INSERT INTO wRykn (id,name,pwd) VALUES (null, 'n1mp', 'Csel4dT7oYpb0zygRMtEHHjO9');
INSERT INTO wRykn (id,name,pwd) VALUES (null, 'Drc', 'KfPluRCYBVkv');
INSERT INTO wRykn (id,name,pwd) VALUES (null, 'J4GrQhKn9Kk', 'It5HOobWa4Novbu0');
SELECT * FROM example  WHERE name="Cq40SOJ8Kx4mPly973Lsh";
INSERT INTO wRykn (id,name,pwd) VALUES (null, 'GaC0ggPvl7j', '6isJ4');
INSERT INTO wRykn (id,name,pwd) VALUES (null, 'DLrTT2evmBmUChVZNGJYw', 'edLSWFhn426Te2pzMU');
SELECT * FROM example  WHERE name="6X";
SELECT * FROM example  WHERE name="ZN1I";
INSERT INTO wRykn (id,name,pwd) VALUES (null, 'J', 'FeR1perD');
SELECT * FROM example  WHERE name="bake222";
INSERT INTO wRykn (id,name,pwd) VALUES (null, 'N', 'fv');
INSERT INTO wRykn (id,name,pwd) VALUES (null, '4zg3WoS', '2jOz6zAJIIsKIfA5r8u74u4A2');
INSERT INTO wRykn (id,name,pwd) VALUES (null, 'UV9neSi4BVHYLKRtCcg8GKohhBrr', 'OX4QDXf1idNkZzboa');
INSERT INTO wRykn (id,name,pwd) VALUES (null, '9mkvgXxuY7', '8pWG9RG6DWtfm2ugsYMg0');
INSERT INTO wRykn (id,name,pwd) VALUES (null, 'wN3FK9EBcBtLYWV74Y', '');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM wRykn  WHERE id=11;
SELECT * FROM wRykn;
SELECT * FROM wRykn  WHERE id=6;
SELECT * FROM wRykn  WHERE name="9B";
