use db;
CREATE TABLE hlQXv (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE id=17;
INSERT INTO hlQXv (id,name,pwd) VALUES (null, 'HlyfdlLAl3GXH2w6f7NQP6qMaCF', 'bf');
INSERT INTO hlQXv (id,name,pwd) VALUES (null, '69LW', 'myXhRDtDY7BVK5OBBEY9Pe9a');
SELECT * FROM example  WHERE id=4;
SELECT * FROM example  WHERE name="wSfHfJQ0EMc0Zn";
SELECT * FROM example  WHERE name="Z6fY9C4sM8zvMtzn6";
SELECT * FROM example  WHERE id=20;
SELECT * FROM example  WHERE id=0;
INSERT INTO hlQXv (id,name,pwd) VALUES (null, 'DdCQ88zh2wrHL95dAUbfgNjA', 'c');
INSERT INTO hlQXv (id,name,pwd) VALUES (null, 'e3riiiW1Jc', 'DKWxfAWlNL10j5Czx2NuJ24');
INSERT INTO hlQXv (id,name,pwd) VALUES (null, 'UmkgdD1UJg7VxO', 'GBSbKoIsgE3mQ');
SELECT * FROM hlQXv  WHERE name="ycLOc96bz";
SELECT * FROM hlQXv  WHERE id=4;
SELECT * FROM hlQXv  WHERE name="LiJO3JfAt3m";
SELECT * FROM hlQXv;
SELECT * FROM hlQXv  WHERE name="";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM hlQXv  WHERE name="JFhSfYPxT93pWKrY51m";
SELECT * FROM hlQXv  WHERE id=5;
