use db;
CREATE TABLE OlZwZ (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM OlZwZ;
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'YQ6aawSyMaphVadzNM7TQCMKjzp', 'HzUQzThwnBus');
SELECT * FROM example  WHERE name="single2019";
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'R2VaOpvWbH3PqNE7XRgTeOXKQPq', 'MxUHoH3QWsiQE7z');
SELECT * FROM example  WHERE name="gaga";
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'HvFUeEFfxTXg', '90riDJ5nqpVsMxLpcu');
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'xuioFD', 'nMPH7sCzPCbqp6rmjbHEfFeLB55h');
SELECT * FROM example  WHERE name="KL2X25xbFpvzYTuUgNZ";
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'vkFLIraV76xShHOECK8QEc9', 'ddb');
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'fehEBDQ2f', 'iT10o25b2ssoaiz');
SELECT * FROM example  WHERE id=12;
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'VUFxslod8WdQgnhDObm9HmlANTXVY', 'Zr');
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'wy4DrYmOwBhkAKcJAVn6t', 'Gh0lxNZx');
SELECT * FROM example  WHERE name="cIXcupOg";
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'nf0eYs7SmlN', 'uq7lpzpRGSISLdfw8l');
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'JxGpNDfJIBwM', '7P3emgLDcR2PKOE');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'r5xao3ixXZ', 'WggubpEO0Gl2DUAx8');
SELECT * FROM example  WHERE name="xrayfighter";
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'i68gCfPT9zGb2CE9hqpEKaw6', 'kJ1fQDTnbjkqex3');
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, '9', 'OoqM8J4jog5CeQJMuL7E1TO');
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'zqJQjvfg63VZ', 'lGlJVdn8Ro');
SELECT * FROM example  WHERE name="SMgnZ6";
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, '9PzNYZglA', 'Y');
SELECT * FROM example  WHERE name="queue";
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'Mws4NEzVFnj84jP1e', 'ZI27GddX');
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'd4w5FUEqWrmj7MTSk5yJTi1', 'bxoVzH68PGtrhDs');
INSERT INTO OlZwZ (id,name,pwd) VALUES (null, 'WDKzNAlLGl2GlM25quXAL', 'deUHVZrCCF82MsdIwNy');
SELECT * FROM OlZwZ  WHERE id=17;
SELECT * FROM OlZwZ  WHERE id=5;
SELECT * FROM OlZwZ  WHERE id=13;
