use db;
CREATE TABLE ntBtp (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO ntBtp (id,name,pwd) VALUES (null, '', 'tBPwNYlDjwJdg3TOY');
SELECT * FROM example  WHERE name="gaga";
SELECT * FROM example  WHERE name="google";
INSERT INTO ntBtp (id,name,pwd) VALUES (null, 'tH4tt', 'TrHCv');
SELECT * FROM example  WHERE id=9;
INSERT INTO ntBtp (id,name,pwd) VALUES (null, 'OJ0', 'M6vzhrW5HXLwu');
SELECT * FROM example  WHERE id=10;
INSERT INTO ntBtp (id,name,pwd) VALUES (null, 'QMI5zPPIgprkkfJ0cvYv0M8GU9', 'FvvufyzRFXxbuH');
INSERT INTO ntBtp (id,name,pwd) VALUES (null, 'qVJXiFrDmbkrvMraDyyWl2', 'GHF0mKNsR1Cx');
INSERT INTO ntBtp (id,name,pwd) VALUES (null, 'Y7fbL7xtbfRZcft8U9CAyEK', 'RwTXKgrD49VR');
SELECT * FROM example  WHERE id=16;
INSERT INTO ntBtp (id,name,pwd) VALUES (null, 'XQWrBUlDNtzxY9AaROj', 'kBhINKSaIcz2M4l');
SELECT * FROM example  WHERE name="A4Avjyyg5BlkeZyOdEXCDjWiETKx";
INSERT INTO ntBtp (id,name,pwd) VALUES (null, 'lQgbXjC8', 'e84GHxU4');
INSERT INTO ntBtp (id,name,pwd) VALUES (null, 'ijMe', 'm31e6k0lZ1');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM ntBtp  WHERE id=8;
SELECT * FROM ntBtp  WHERE name="4q4ibu9sWB";
SELECT * FROM ntBtp  WHERE id=3;
SELECT * FROM ntBtp;
