use db;
CREATE TABLE tIatS (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="zookeeper001";
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'p2ZQ6c8CjXH', 'NQmSluVBPHRPpQ1Wwx2');
SELECT * FROM example  WHERE name="varus";
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'q', 'OIKDZuuHYrGRPyokReAmfSoM3uch');
INSERT INTO tIatS (id,name,pwd) VALUES (null, '91eGA1lIkqTZsYD', '63Tacz');
SELECT * FROM example  WHERE id=9;
INSERT INTO tIatS (id,name,pwd) VALUES (null, '2BU3NH', 'gPp6MAOtEX50N4');
INSERT INTO tIatS (id,name,pwd) VALUES (null, '8zTSmXnAan2HWDLy', 'eqLqHJCu2j');
INSERT INTO tIatS (id,name,pwd) VALUES (null, '5mEQ0VQXQ2cG0R', 'odaDusi8ZzhqUOw8A7yKrY13yyqGX');
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'h6H8FsGdPtjI3bJoCTjeVA', 'zTVPwqG0Zypz2Hp30pkOqyA');
SELECT * FROM example  WHERE name="24wkMlpvBB";
SELECT * FROM example  WHERE name="euro";
SELECT * FROM example  WHERE id=15;
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'lxOV4Yemvo7J0bum', 'dBY');
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'MTOAuIygu3cRr6l0', 'dco8MEGdwT');
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'yLkhtfvuvrgWgMazuivj8', 'H6QMmHFRQQGxTTEPNsmnLnGfnq6YK');
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'XV7s', 'IFgbd2Po2amNyMMk0');
INSERT INTO tIatS (id,name,pwd) VALUES (null, '8qzXsfWdnUD', 'rHkntSNcPZEdgVeEPHMCE6L55Qa');
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'pT', '4Q3i6cTlJ2d6ta7k3xx2L4ZAKTfj4');
SELECT * FROM example  WHERE name="restinpeace";
SELECT * FROM example  WHERE name="hEYvt4C8mpBt8AON3nr";
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'p', 'MANER');
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'pA3zuOQWotT', 'Z5WCXYA77S3eIH');
INSERT INTO tIatS (id,name,pwd) VALUES (null, 'pEHuic4VJXGqB52', 'C4eXUdjW0khktJomT');
SELECT * FROM tIatS  WHERE name="BMG";
SELECT * FROM tIatS;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM tIatS  WHERE id=4;
SELECT * FROM tIatS  WHERE id=9;
SELECT * FROM tIatS  WHERE name="gglZetMjilpN2zhcFhnnEOK";
SELECT * FROM tIatS  WHERE name="yiqv6xgx";
SELECT * FROM tIatS  WHERE name="";
