use db;
CREATE TABLE YXnYu (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO YXnYu (id,name,pwd) VALUES (null, 'rkdhIoWGzXH2HF2QJPjYQM66', 'NYjwif24TWYvpQhCZDLR');
SELECT * FROM example  WHERE name="test";
SELECT * FROM example  WHERE name="euro";
SELECT * FROM example  WHERE id=6;
INSERT INTO YXnYu (id,name,pwd) VALUES (null, 'EHvQ42P2', 'Qca');
SELECT * FROM example  WHERE id=19;
INSERT INTO YXnYu (id,name,pwd) VALUES (null, '0Q9GBM8szrbNJ', '1TYVKHDTal83vkB2DhbDh5Ip');
INSERT INTO YXnYu (id,name,pwd) VALUES (null, 'ofwolkf', 'k');
SELECT * FROM example  WHERE name="notebook";
INSERT INTO YXnYu (id,name,pwd) VALUES (null, 'hLr5cN5CfOrsM', 'xIB');
SELECT * FROM YXnYu;
INSERT INTO YXnYu (id,name,pwd) VALUES (null, 'A28A5HKB', 'LE0yfLamilBOdyZa2WbIlIcwsY');
INSERT INTO YXnYu (id,name,pwd) VALUES (null, '', 'Rrx1ZcPQp96dIO5TtYr37ieDPrB9o');
SELECT * FROM example  WHERE name="jfQWijMDBYPBWnTSiS1VVHVEVj";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE id=4;
INSERT INTO YXnYu (id,name,pwd) VALUES (null, 'sKmyvgzgR0y', 'wMHqu');
SELECT * FROM example  WHERE id=9;
SELECT * FROM YXnYu  WHERE name="BnkR14neRpc7OzQl8nDl6";
