use db;
CREATE TABLE rDaWb (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="Ayv8rj6pNT3PqpbM";
SELECT * FROM example  WHERE id=6;
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'NJKqW1MmLpPbDwLp0eRs', 'rrDzJ9ADp9Njmmkgp7TLzieHV');
INSERT INTO rDaWb (id,name,pwd) VALUES (null, '7lGV42O9', 'MoTz');
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'K8fyo5P0Pi0SzIXF5zh95MvH', 'i4wB970nIfz1gnS6JUf');
INSERT INTO rDaWb (id,name,pwd) VALUES (null, '26apvkwIfC7', 'l');
SELECT * FROM example  WHERE id=2;
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'jgN', '');
SELECT * FROM example  WHERE id=8;
SELECT * FROM example  WHERE name="iterations";
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'gl', 'hpXTmlyst5');
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'UMRL6PkIhGtvQafj4h', 'z1dkIKZbIAlAIx');
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'hYr9oG0pntg3TYf3O', 'v5qYusc9Svx6yS2iVZwjArfxSn0');
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'j4V30oqlA6dG9gvgck52szY8', '8gwbllij4OKHVNlLIT');
SELECT * FROM example  WHERE name="bob!!!";
INSERT INTO rDaWb (id,name,pwd) VALUES (null, '4ry', 'j7PFnL');
SELECT * FROM example  WHERE id=2;
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'lLQlY', 'dLr5HY');
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'pxVTwe5rT3JUpxigR3c2LLFy', 'x6NQ1Ir5');
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'hSjT71cBSgeqE8Y6nwmL1k2fX', 'IZFfc');
SELECT * FROM example  WHERE name="kdimentions";
INSERT INTO rDaWb (id,name,pwd) VALUES (null, '2W6wbVVGxsZbLBpD9jYATBu', 'QZiO1m');
INSERT INTO rDaWb (id,name,pwd) VALUES (null, 'el', 'NNHd9DQ8MJ');
INSERT INTO rDaWb (id,name,pwd) VALUES (null, '3Rrmle2P', 'vAdNAiaY3f2j645pf');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM rDaWb;
SELECT * FROM rDaWb  WHERE id=7;
SELECT * FROM rDaWb  WHERE name="ARTFzEnxuAbxEHWJEjre7NIPD2IZ";
SELECT * FROM rDaWb  WHERE id=14;
SELECT * FROM rDaWb  WHERE id=5;
SELECT * FROM rDaWb  WHERE id=11;
