use db;
CREATE TABLE PQzNT (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO PQzNT (id,name,pwd) VALUES (null, 'PXAm4xXeWTJrpZm', 'KESR');
INSERT INTO PQzNT (id,name,pwd) VALUES (null, 'yxYWvlI02owKedn18J', 'DPfZCOw');
INSERT INTO PQzNT (id,name,pwd) VALUES (null, 'cHMEgFP0pz5MLm45JLC5bIsIOHPL', 'iIBRke3WRhHhOqsiV0rHUn');
INSERT INTO PQzNT (id,name,pwd) VALUES (null, 'NPSdpOAmFzRG7MBl6qONJvd4', 'lUJRZb');
INSERT INTO PQzNT (id,name,pwd) VALUES (null, 'nsE69LpEZokj8goFGcYKM4G6NaTWE', 'RFS');
INSERT INTO PQzNT (id,name,pwd) VALUES (null, 'ey', 'GgZwsrN');
INSERT INTO PQzNT (id,name,pwd) VALUES (null, '6q3Nr3LT5xt6XYJKAYRyoQdY', 'qxekPZpxpcePZOPmdzmSQPToZHk');
SELECT * FROM example  WHERE id=13;
SELECT * FROM example  WHERE id=4;
SELECT * FROM example  WHERE id=18;
INSERT INTO PQzNT (id,name,pwd) VALUES (null, '3AfogUr8Rm4t0nx', 'WoYnA0KkiuZ3');
INSERT INTO PQzNT (id,name,pwd) VALUES (null, 'K6hKX', 'cbJ1FtVOpyYinhJZxgyI38P');
SELECT * FROM example  WHERE name="ZFG";
INSERT INTO PQzNT (id,name,pwd) VALUES (null, 'vCU5B', 'Jfa');
SELECT * FROM PQzNT;
SELECT * FROM PQzNT  WHERE id=1;
SELECT * FROM PQzNT  WHERE id=9;
SELECT * FROM PQzNT  WHERE id=10;
SELECT * FROM PQzNT  WHERE id=4;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
