use db;
CREATE TABLE BMytY (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="fRX0aSiTijWe2mlf8nGQRjBcYVH";
INSERT INTO BMytY (id,name,pwd) VALUES (null, 'eDV', 'rD5gBBzD6bmFXaaXIRHLQzTMF');
SELECT * FROM BMytY;
INSERT INTO BMytY (id,name,pwd) VALUES (null, 'Y42', 'iSt7G2wrRybCL77qZw7wVoI6KZ');
INSERT INTO BMytY (id,name,pwd) VALUES (null, 'wqg', '0pX7OAwiCkIRG9fABFmBfqNRrsK05');
INSERT INTO BMytY (id,name,pwd) VALUES (null, 'DBLFwhJmrzyIVdYuBVeNo8YVTFfxg', '7tr4fIPA8FELFnynv');
SELECT * FROM example  WHERE name="hello";
INSERT INTO BMytY (id,name,pwd) VALUES (null, 'xCrX6uwqjrsKoJfZNBSA0w2fh', 'HpwZrJDw7CSUzktt');
INSERT INTO BMytY (id,name,pwd) VALUES (null, 'bl', 'UOw6jLKGHOO4VnZc8PwCKz2uNTUJZ');
INSERT INTO BMytY (id,name,pwd) VALUES (null, 'rlnoFxzrxTi', 'XRHnlTpuz8oPsN0qq6');
SELECT * FROM example  WHERE name="mickeymouse";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO BMytY (id,name,pwd) VALUES (null, 'ofOhFO', 'cvtUbvsFWZvFVE8uAcr2msL2');
INSERT INTO BMytY (id,name,pwd) VALUES (null, 'DZrQz7ZEiEYqmOJ6GpLMmB6or70Tb', 'UsGsZBFYcPGViKnlYGDGsgunsDY0');
SELECT * FROM example  WHERE name="cathy3333";
INSERT INTO BMytY (id,name,pwd) VALUES (null, '6tWd6QnIIZ1kTn', 'KWvs2p');
INSERT INTO BMytY (id,name,pwd) VALUES (null, 'fSJJh9Kjch2', 'XCqRC');
SELECT * FROM BMytY  WHERE name="9KCNjFQ9tDRTbi6bXOLSgoVGJdt";
SELECT * FROM BMytY  WHERE id=8;
SELECT * FROM BMytY  WHERE id=10;
SELECT * FROM BMytY  WHERE id=6;
SELECT * FROM BMytY  WHERE id=8;
SELECT * FROM BMytY  WHERE name="NOfLlKiAk1U4z7o8Wy3ykOLuo0";
