use db;
CREATE TABLE xwUqh (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="pinchen";
INSERT INTO xwUqh (id,name,pwd) VALUES (null, '0XJMVaVIWxRMPXIbIgWPzNSy7Qc', 'Ulmj3vsQTq7Bq46LsyesDL02Kzwu');
INSERT INTO xwUqh (id,name,pwd) VALUES (null, 'WwuBNCOSJU6wTp3f', 'w1ON3jhL0ok3NBJ');
SELECT * FROM example  WHERE id=2;
INSERT INTO xwUqh (id,name,pwd) VALUES (null, 'ZVv0CQAQE5', 'Iu0Ey7hQEt9z9ZAzABgn1N');
INSERT INTO xwUqh (id,name,pwd) VALUES (null, '336upJg4b', 'nO1GtzWiLUQ');
INSERT INTO xwUqh (id,name,pwd) VALUES (null, '5', 'Kzg3iAZOGTMU2AQnUROnT');
SELECT * FROM example  WHERE name="LoGkuWAB2z6HsMG87KTRbX";
SELECT * FROM xwUqh;
INSERT INTO xwUqh (id,name,pwd) VALUES (null, 'RchfWWcjg', '');
SELECT * FROM example  WHERE name="5Fp2yH3e78KjKJpxvZt5i6mS";
INSERT INTO xwUqh (id,name,pwd) VALUES (null, 'WJLUaMGDkYrIfqt', 'Z6IyI7MnshMsu');
INSERT INTO xwUqh (id,name,pwd) VALUES (null, 'gQWDS', 'U2eYerUzT');
INSERT INTO xwUqh (id,name,pwd) VALUES (null, '', 'XQNMCLjUN8p');
INSERT INTO xwUqh (id,name,pwd) VALUES (null, 'UkS6i96OYjXNHjZJm', 'GXXE');
INSERT INTO xwUqh (id,name,pwd) VALUES (null, '1o9QL0xJ1', 'Lhd3sRcEc');
INSERT INTO xwUqh (id,name,pwd) VALUES (null, '63ww', '1J5G42ddhyWiJrgngk0VXs');
SELECT * FROM example  WHERE name="elephant";
SELECT * FROM example  WHERE id=20;
INSERT INTO xwUqh (id,name,pwd) VALUES (null, 'SKtT3GIw20SpNJRlh', '5Lwy');
INSERT INTO xwUqh (id,name,pwd) VALUES (null, 'W2pclvNrgwkV', 'LSYRuL');
SELECT * FROM example  WHERE name="x04OMPvjt0y14VZROR5L";
INSERT INTO xwUqh (id,name,pwd) VALUES (null, '92nYu9771hauMJ7V2', 'N2SmRCrq1GgI5oluKj5TF81xtoB');
INSERT INTO xwUqh (id,name,pwd) VALUES (null, 'zrQbmn3gSdO', 'Xo16sUnFkC');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM xwUqh  WHERE name="xEVv6qBdT";
SELECT * FROM xwUqh  WHERE name="k65f730W8NFj5jgqVqvMJHsG";
SELECT * FROM xwUqh  WHERE id=10;
SELECT * FROM xwUqh  WHERE name="L";
SELECT * FROM xwUqh  WHERE id=5;
SELECT * FROM xwUqh  WHERE name="dH9E42CZ3LsAPx";
