use db;
CREATE TABLE SsPGB (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="test";
SELECT * FROM example  WHERE id=19;
INSERT INTO SsPGB (id,name,pwd) VALUES (null, 'MAkKeXA8sko69Gr0alEn', 'YQMaCvuyF2qT7w0kJ');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO SsPGB (id,name,pwd) VALUES (null, '1a8Ciq4IFk5Bb6YzTTeRx', 'calssCcHs0XunBUyt3xBh8mTJReM');
SELECT * FROM example  WHERE name="Fa3fXVOa2o4hCJGa";
SELECT * FROM example  WHERE name="letsparty";
INSERT INTO SsPGB (id,name,pwd) VALUES (null, 'QrWVCEtKEIhOl2mYl3VH7Mx9', '8fgNbaddY1rbpKBqM20N');
INSERT INTO SsPGB (id,name,pwd) VALUES (null, 'FKJzwA4mDLAOvU', 'as3cTi9AAN');
SELECT * FROM example  WHERE name="euro";
SELECT * FROM example  WHERE name="cathy3333";
SELECT * FROM SsPGB;
SELECT * FROM example  WHERE name="p15ZMfGheYOqt9jHDxLT";
SELECT * FROM example  WHERE name="F7oFlxECdSnhXjMDD3Y6QH";
SELECT * FROM example  WHERE name="1XJh5mdt8eDGAExNGED";
SELECT * FROM example  WHERE id=7;
SELECT * FROM example  WHERE id=1;
SELECT * FROM SsPGB  WHERE id=3;
SELECT * FROM SsPGB  WHERE name="Cjoh4dT1T0Ay5NFaPsbBcFuQU9";
SELECT * FROM SsPGB  WHERE name="GAXX35fcIriZXlfdPoMa0Vf";
SELECT * FROM SsPGB  WHERE id=0;
SELECT * FROM SsPGB  WHERE name="WGV7VWts";
