use db;
CREATE TABLE unuwF (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO unuwF (id,name,pwd) VALUES (null, 'I5FaZBM5Y5tMB', '');
INSERT INTO unuwF (id,name,pwd) VALUES (null, 'cGXPZCSBUm6', 'qdiYZjtq2');
INSERT INTO unuwF (id,name,pwd) VALUES (null, 'DXq9pyIqIYKhitcR', 'G5uLLlmFP1EWXUIdJOpdNU');
SELECT * FROM example  WHERE id=19;
SELECT * FROM example  WHERE id=20;
SELECT * FROM example  WHERE id=19;
INSERT INTO unuwF (id,name,pwd) VALUES (null, 'tWw0NryRMqPEjiF7FhdIuAMTD', 'WHpaR3opZKeDpkjjA5c9c');
INSERT INTO unuwF (id,name,pwd) VALUES (null, 'gEl9uGiOUrSRH1mgwtjDOZJ', 'TMKs2XvqGrPf2fdHrPTmWXwlC');
SELECT * FROM example  WHERE name="italy1912";
SELECT * FROM example  WHERE id=0;
INSERT INTO unuwF (id,name,pwd) VALUES (null, 'YTxckvuTUPK87zNL1nLX80al9', '5Yosinr');
SELECT * FROM example  WHERE name="orthogonal";
INSERT INTO unuwF (id,name,pwd) VALUES (null, 'CjUetQghQM3Ur9DtidWtd', 'Z4DpxEY');
SELECT * FROM unuwF  WHERE name="zIDZqyd8h77qPTuttzyNhk7iHDTW4";
SELECT * FROM unuwF  WHERE id=0;
SELECT * FROM unuwF  WHERE id=1;
SELECT * FROM unuwF;
SELECT * FROM unuwF  WHERE name="fFwAIorue";
SELECT * FROM unuwF  WHERE id=5;
SELECT * FROM unuwF  WHERE id=3;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
