use db;
CREATE TABLE KErag (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO KErag (id,name,pwd) VALUES (null, 'WVlUkcuqE3Dwc1L', 'LkpiKz3Re1di');
INSERT INTO KErag (id,name,pwd) VALUES (null, 'REHgXvv9yRHu', 'rvqbNAMa72wBSjxmFcE');
INSERT INTO KErag (id,name,pwd) VALUES (null, 'ZdSfKQOvCfqfZhE', 'LtcTcXkyaV1NXRulmDXPVwaYTr9');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM KErag;
SELECT * FROM example  WHERE name="tosEX7YbK6kt";
SELECT * FROM example  WHERE id=11;
SELECT * FROM example  WHERE name="a4Cdq9iyHIot";
INSERT INTO KErag (id,name,pwd) VALUES (null, 'QwH9dEVwbkes1ejwkBe7ugcD23P6n', 'bqSP4v0wEWXwX');
INSERT INTO KErag (id,name,pwd) VALUES (null, 'j5XDVqunRA', 'v');
SELECT * FROM example  WHERE id=2;
SELECT * FROM example  WHERE name="8NSCz5hjTe";
INSERT INTO KErag (id,name,pwd) VALUES (null, '0R1ZqWihF6EvcEIioxvbii', '0T3VSE');
INSERT INTO KErag (id,name,pwd) VALUES (null, 'KGGS', '');
SELECT * FROM example  WHERE name="orthogonal";
INSERT INTO KErag (id,name,pwd) VALUES (null, 'IpgHZpqpwyTApyajmsBNByY9fwKXl', 'QdhKP6GMSrnQ3Rqh5P');
INSERT INTO KErag (id,name,pwd) VALUES (null, 'ETO8o', 'vTziFPBHYjiCvdBK1Gl4GZT');
SELECT * FROM KErag  WHERE name="cgLe";
SELECT * FROM KErag  WHERE id=0;
SELECT * FROM KErag  WHERE id=6;
SELECT * FROM KErag  WHERE name="fSpuBF2FXWo7z67CN1dv";
SELECT * FROM KErag  WHERE name="Sk1LOkK1sZzywsGD6QSw6Hmu";
