use db;
CREATE TABLE dXcdA (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO dXcdA (id,name,pwd) VALUES (null, 'DLF1w9jjEMXukj7cVu8D2hUJRg', 'HkwN6vTr71YG');
INSERT INTO dXcdA (id,name,pwd) VALUES (null, 'c9', 'Ke5ohWHoVZ8J7S');
SELECT * FROM example  WHERE name="oppo";
SELECT * FROM dXcdA;
SELECT * FROM example  WHERE id=1;
SELECT * FROM example  WHERE id=0;
INSERT INTO dXcdA (id,name,pwd) VALUES (null, '1REp0td8fho2tAeJY0r3F1iT', 'BLVBQglE6U6SYGjw3rQ0');
SELECT * FROM example  WHERE id=12;
SELECT * FROM example  WHERE name="C";
INSERT INTO dXcdA (id,name,pwd) VALUES (null, 'mgRhT5ZxLPNkM31IMmkRyuSxACpt', 'mWD95iIJDL9in');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE name="Vdz";
SELECT * FROM example  WHERE name="um92dxdYTkRkBQrXQw7";
SELECT * FROM example  WHERE name="iterations";
SELECT * FROM example  WHERE name="queenofthrone";
INSERT INTO dXcdA (id,name,pwd) VALUES (null, 'I2WYdkOtGgkV', 'i9CUEaeXjXxLkJdK0EuJj7xF9x');
INSERT INTO dXcdA (id,name,pwd) VALUES (null, '4gzDQLcfL9zh0epPSyoU7Hr', 'X8GO6wOUtcVvG50uMbzVCGjCx');
INSERT INTO dXcdA (id,name,pwd) VALUES (null, 'oUnOVi', 'eu0Tp6bM9aIT');
SELECT * FROM dXcdA  WHERE name="G737656yRcADB";
SELECT * FROM dXcdA  WHERE name="a1n6A8PIfnzCj";
