use db;
CREATE TABLE BTEVm (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE id=3;
INSERT INTO BTEVm (id,name,pwd) VALUES (null, 'OhbonpxXws6OuZ3DT0z', '7oGfg2ouOXR68xKMy2BQ2CC');
SELECT * FROM example  WHERE name="eziaRXf";
SELECT * FROM example  WHERE name="cici1001";
INSERT INTO BTEVm (id,name,pwd) VALUES (null, 'VbicI6RJFHWMl', 'Kfx5xJLYNlqHjM4');
INSERT INTO BTEVm (id,name,pwd) VALUES (null, 'OqxsWvKozerHIFXu3x5FjyMMdmX', 'B');
SELECT * FROM example  WHERE name="PG3ac0IsHWfcWZhArKY9zDGrXxjAs";
INSERT INTO BTEVm (id,name,pwd) VALUES (null, '5j97ggDLK51NYFkmJ', 't');
INSERT INTO BTEVm (id,name,pwd) VALUES (null, '6XN9rghgNCY9HBDZ26wSRO', 'qLkx2audmVF');
INSERT INTO BTEVm (id,name,pwd) VALUES (null, '53Twomme6aaGudDbXALgCIfi', 'MJX4dwVWd7A1xk');
SELECT * FROM example  WHERE id=5;
SELECT * FROM example  WHERE id=11;
INSERT INTO BTEVm (id,name,pwd) VALUES (null, 'ZmcvtKlkOWMhm8QhzsmblAzh5', 'UTVvfRGQ5OVkUY8gAiaJt');
INSERT INTO BTEVm (id,name,pwd) VALUES (null, 'YRPLBy2vPft', 'x9OVxR8JPw2qQlXrfIn');
SELECT * FROM example  WHERE name="mickeymouse";
INSERT INTO BTEVm (id,name,pwd) VALUES (null, 'zaBAPm', 'fI46KQjdZioRZR8jgUhwOJ9TT');
INSERT INTO BTEVm (id,name,pwd) VALUES (null, 'nlN8xbIuF2', 'Jh5zkr00');
SELECT * FROM example  WHERE name="a5pqXxejWvVeRa1buVi5fQzJLdqw2";
INSERT INTO BTEVm (id,name,pwd) VALUES (null, 'RnDRHFeHk7qwfWSgG', 'FndpGiu4Hadr7GXj1CkehyTnAHu');
SELECT * FROM example  WHERE name="yuhateme";
SELECT * FROM example  WHERE name="P2Ed93ogwBR";
INSERT INTO BTEVm (id,name,pwd) VALUES (null, 'J', '6VIaHMfnl3JyL2kEHN');
SELECT * FROM example  WHERE id=15;
SELECT * FROM BTEVm  WHERE id=0;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM BTEVm;
SELECT * FROM BTEVm  WHERE id=12;
SELECT * FROM BTEVm  WHERE name="8iQke3uFoz7YFc";
SELECT * FROM BTEVm  WHERE id=3;
SELECT * FROM BTEVm  WHERE name="V";
