use db;
CREATE TABLE UEGWO (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO UEGWO (id,name,pwd) VALUES (null, 'W7JPzTt', 'PWYsuXwGym4q');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM UEGWO;
SELECT * FROM example  WHERE name="friend";
SELECT * FROM example  WHERE name="QOHvDhFrM5mD";
INSERT INTO UEGWO (id,name,pwd) VALUES (null, 'ESVJXgtLDCUBr8EYFIcOiK3be8haT', 'BSM0Swe6zVDfH5fyPx');
INSERT INTO UEGWO (id,name,pwd) VALUES (null, 'wzT03', 'yQjdcKQ0IMWcdAmRX');
SELECT * FROM example  WHERE id=5;
INSERT INTO UEGWO (id,name,pwd) VALUES (null, 'HM', 'sf');
SELECT * FROM example  WHERE name="papi";
SELECT * FROM example  WHERE id=4;
SELECT * FROM example  WHERE name="ufortable";
SELECT * FROM example  WHERE name="zookeeper001";
SELECT * FROM UEGWO  WHERE id=1;
SELECT * FROM UEGWO  WHERE id=4;
SELECT * FROM UEGWO  WHERE id=2;
SELECT * FROM UEGWO  WHERE id=1;
