use db;
CREATE TABLE Ptisa (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO Ptisa (id,name,pwd) VALUES (null, '', 'Qqgnqe2szUNkLLWrO9ft3j');
INSERT INTO Ptisa (id,name,pwd) VALUES (null, 'b3yRWmSYfPQBzKngrwh', 'OyRR8Tk4w8wPj5KADKe3');
SELECT * FROM example  WHERE id=14;
SELECT * FROM example  WHERE name="t70WOrB9GUQfnoPmEfOxlR";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE id=20;
INSERT INTO Ptisa (id,name,pwd) VALUES (null, 'wR1VK3Q5AKfdTT', 'pgfYrKvlrZ');
SELECT * FROM example  WHERE id=1;
INSERT INTO Ptisa (id,name,pwd) VALUES (null, 'xlNUPWxvYrB5K3d', 'iQQAKu90');
INSERT INTO Ptisa (id,name,pwd) VALUES (null, 'sRuZ0x6E4fQCTD6roafuDwEMn', '8lheyjpzT5D');
INSERT INTO Ptisa (id,name,pwd) VALUES (null, 'Rsf6BTOnp', 'j0mteH1wOKMlufKSyPIzUAHrcnR');
SELECT * FROM example  WHERE id=13;
INSERT INTO Ptisa (id,name,pwd) VALUES (null, 'O6Lelv5OuYI', 'ldodjUJVkmZZAXHrr9');
INSERT INTO Ptisa (id,name,pwd) VALUES (null, 'lTuNkkp1SFwca7ev0yT', '7p6sVJpRWfkYVYl9IL');
INSERT INTO Ptisa (id,name,pwd) VALUES (null, 'KXHnVKpNe', 'ergX');
INSERT INTO Ptisa (id,name,pwd) VALUES (null, 'i', 'H0sVY2lYlg1nZey8JMVz');
SELECT * FROM example  WHERE name="Suqa";
INSERT INTO Ptisa (id,name,pwd) VALUES (null, '26SJhzUBB1G9Mdtz5SBf', 'M1FXfudZAI076r48NyZ8uXnjC');
SELECT * FROM Ptisa;
SELECT * FROM example  WHERE name="pD0UmyK3rHyMdIMSLyJ46";
SELECT * FROM example  WHERE name="8wc49vepwcA79Pdb3ZYKivsQYMUz";
SELECT * FROM Ptisa  WHERE id=10;
SELECT * FROM Ptisa  WHERE id=10;
SELECT * FROM Ptisa  WHERE id=4;
SELECT * FROM Ptisa  WHERE name="VnjgZfmz2GLxYUEohvQN";
SELECT * FROM Ptisa  WHERE name="6xe3ONEvAjGfUqfpoaw3qaIp";
SELECT * FROM Ptisa  WHERE name="dyECrfneBd";
