use db;
CREATE TABLE LoLxz (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO LoLxz (id,name,pwd) VALUES (null, 'KYjZ', '5al9L56QCpoybRr4rwUSC1');
INSERT INTO LoLxz (id,name,pwd) VALUES (null, 'Wgv', 'dH2iLKGHRv0lmppMfpg');
SELECT * FROM example  WHERE name="ufortable";
INSERT INTO LoLxz (id,name,pwd) VALUES (null, 'BwjzCdd2p8lDbFcn', 'eAV2N');
SELECT * FROM example  WHERE id=0;
INSERT INTO LoLxz (id,name,pwd) VALUES (null, '0', 'tZRc');
INSERT INTO LoLxz (id,name,pwd) VALUES (null, 'oBpGx5MAz3AiIZdGR9W046F20lg', 'TLvM');
INSERT INTO LoLxz (id,name,pwd) VALUES (null, 'LbTLb0Feekt5U0zgy029euqu', 'x0Zzkt2bWYRPwEvg1M1UvXqqq');
INSERT INTO LoLxz (id,name,pwd) VALUES (null, '9W', 'RbNhZ1H2ZLky9z70VBiiBqO30fCeV');
INSERT INTO LoLxz (id,name,pwd) VALUES (null, '5llC7uSB', '9uJGeh6tl6g2xWaTFfib');
SELECT * FROM example  WHERE id=8;
INSERT INTO LoLxz (id,name,pwd) VALUES (null, '2Mz2T', 'SeUfd2cD2b4K8PzRDJSG');
INSERT INTO LoLxz (id,name,pwd) VALUES (null, 'DHZKtfEuJN0YFQXLSoho0tHittfh2', 'FlmJqsgql2QNfQNGHPgTbbkCf');
INSERT INTO LoLxz (id,name,pwd) VALUES (null, '', 'WpUH83A5kde6zGlTLRXyJ1');
SELECT * FROM example  WHERE id=2;
INSERT INTO LoLxz (id,name,pwd) VALUES (null, 'H8sco1', 'D9NZsVZ0966P8m');
INSERT INTO LoLxz (id,name,pwd) VALUES (null, 'jLWhGL1c0M3V6', 'MwCv5zyyJkQHKqQklI');
SELECT * FROM example  WHERE name="hollywood36830";
INSERT INTO LoLxz (id,name,pwd) VALUES (null, '', 'IZC');
INSERT INTO LoLxz (id,name,pwd) VALUES (null, 'd8hynt7pf5Bs', 'xB');
SELECT * FROM example  WHERE id=18;
INSERT INTO LoLxz (id,name,pwd) VALUES (null, 'qYlC7V', 'BwBvhZYmXBPgEF4ANsaG');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM LoLxz  WHERE id=9;
SELECT * FROM LoLxz;
