use db;
CREATE TABLE tzTNX (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE id=7;
SELECT * FROM example  WHERE name="italy1912";
INSERT INTO tzTNX (id,name,pwd) VALUES (null, 'FiNJupRzYXspqtKWxPu', '2Luuqyku62x46rXj4PZAoxWDVb');
SELECT * FROM example  WHERE id=4;
SELECT * FROM example  WHERE id=3;
SELECT * FROM example  WHERE id=6;
SELECT * FROM example  WHERE name="single2019";
SELECT * FROM example  WHERE name="joke";
SELECT * FROM tzTNX  WHERE id=1;
SELECT * FROM tzTNX  WHERE id=0;
SELECT * FROM tzTNX  WHERE id=1;
SELECT * FROM tzTNX  WHERE name="6Avh0iV9zrq6aDkNUh91DWZRija";
SELECT * FROM tzTNX  WHERE id=1;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM tzTNX  WHERE name="QRI2FbhlZkzfV";
SELECT * FROM tzTNX;
