use db;
CREATE TABLE nWwUr (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO nWwUr (id,name,pwd) VALUES (null, '4NQDR6jdghKLA', 'RiezxtvMeaagfC');
INSERT INTO nWwUr (id,name,pwd) VALUES (null, 'Pu4HisSusAt', '6sDHQ');
INSERT INTO nWwUr (id,name,pwd) VALUES (null, 'Ck3ITqAz2grUQ', 'Lg8dYB38UwAn66h');
INSERT INTO nWwUr (id,name,pwd) VALUES (null, 's9u5LYpmyBT9h1szi', 'IeatIaBrBx2apw');
SELECT * FROM example  WHERE name="mcdonalds";
INSERT INTO nWwUr (id,name,pwd) VALUES (null, 'v', 'VRHfx');
INSERT INTO nWwUr (id,name,pwd) VALUES (null, 'CA2uPWXE9VqqjBF3UhZ5THVR', 'iZhPvq5MszVjvqIR28eFN');
INSERT INTO nWwUr (id,name,pwd) VALUES (null, '8RfDLX43ZCBMkmPiipj7aSTL', 'wcPwk22zhLW3JK8eFg');
INSERT INTO nWwUr (id,name,pwd) VALUES (null, 'ozFGHCts', 'zSufIKW9YA0Tbnj3HYvIKoVm7c9yg');
SELECT * FROM example  WHERE name="";
INSERT INTO nWwUr (id,name,pwd) VALUES (null, 'FV5jPcIS1d', 'qswxi4GKwXTnDelI1fF3capL');
INSERT INTO nWwUr (id,name,pwd) VALUES (null, 'uhuvaq5XlKOttZLZeQw8', 'JPd4rLX195NseCAqE9jjqzHbAY');
INSERT INTO nWwUr (id,name,pwd) VALUES (null, '1oSHzAkZEtPpj4btuTnERVwO6QB', '6lBtFm8ASzSwKk');
SELECT * FROM example  WHERE name="Pwk43aROl";
SELECT * FROM example  WHERE name="Qt1woYeZr5WzeJPavLIP525TMT8";
SELECT * FROM nWwUr;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO nWwUr (id,name,pwd) VALUES (null, 'f', 'c31j0G11');
SELECT * FROM example  WHERE name="Jo5CMNEp7Ou61xjw";
INSERT INTO nWwUr (id,name,pwd) VALUES (null, '6HjPpyUbR0gebSbLugqrGpI', 'uBsKAqhn50SX5ua');
INSERT INTO nWwUr (id,name,pwd) VALUES (null, '0b2LRDKMI7EDixGUHvInnOlM', 'M9OwTJ');
INSERT INTO nWwUr (id,name,pwd) VALUES (null, 'Kr', '3QzU6sRuOFg0MayS1yp5wpux2hpd');
SELECT * FROM nWwUr  WHERE name="KaMyNACiIvA9IB72vkKJR";
SELECT * FROM nWwUr  WHERE id=12;
SELECT * FROM nWwUr  WHERE id=14;
SELECT * FROM nWwUr  WHERE id=5;
SELECT * FROM nWwUr  WHERE id=3;
