use db;
CREATE TABLE mrgyu (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO mrgyu (id,name,pwd) VALUES (null, 'wr3yi8vzEdPsZtG0cpD', 'u48yVu0dz97Oh6nGo');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO mrgyu (id,name,pwd) VALUES (null, 'usHkG3TaclTDm2An0NgK0O', '71CejdCu3vDBCJS9');
INSERT INTO mrgyu (id,name,pwd) VALUES (null, 'exOOWZRMfKcxzreyiatsY', 'U9BiMnQPU28ZTRdr65AxVTBGINVfw');
INSERT INTO mrgyu (id,name,pwd) VALUES (null, 'NriNsgLR3q4ES223r', 'B60E1OwebCpBQVytYgyaF');
INSERT INTO mrgyu (id,name,pwd) VALUES (null, 'DykqjxLb', '9b9lVgXhv9Ymn5kpcRgqZv');
SELECT * FROM example  WHERE name="2R3Ix9VEUsSU2";
INSERT INTO mrgyu (id,name,pwd) VALUES (null, 'ZrlIwhnNg', 'BL9YH2dzkDd2aNRnKDkKKp23S');
INSERT INTO mrgyu (id,name,pwd) VALUES (null, '4TQpT40u11b', '');
SELECT * FROM example  WHERE name="hPXxN4wlf5B1ps5tfUIaqCOVq4Ng";
INSERT INTO mrgyu (id,name,pwd) VALUES (null, 'PB7CGo8ZeRQdy0ndNOzi1', '2vQZ9o0MmJPZDHnwKiuN38Y0dxip');
SELECT * FROM mrgyu;
INSERT INTO mrgyu (id,name,pwd) VALUES (null, '6aCvmhq', 'ty');
INSERT INTO mrgyu (id,name,pwd) VALUES (null, 'QL6EfrWyKwD9uc1ChFhjZj', 'NabRDYBJMgJO2JIyNb1wvT1ZlUkOK');
SELECT * FROM example  WHERE name="wickedbanana";
INSERT INTO mrgyu (id,name,pwd) VALUES (null, '5OwN', '17AmCKSmrKWs1h5x');
INSERT INTO mrgyu (id,name,pwd) VALUES (null, 'aKiDpgkfqhjewulg', '');
INSERT INTO mrgyu (id,name,pwd) VALUES (null, 'brWnx0MO2KHNtlUawGQZ4g', 'viH8mtQnDXtmd0');
SELECT * FROM mrgyu  WHERE name="WZyRaRW";
