use db;
CREATE TABLE lsAqn (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO lsAqn (id,name,pwd) VALUES (null, 'si29DJ', '1x0UeoXZC');
SELECT * FROM example  WHERE id=13;
INSERT INTO lsAqn (id,name,pwd) VALUES (null, 'hx4rseYFA', 'suVVQ1de15u4B7Kv4NXyvd4UtCoF6');
INSERT INTO lsAqn (id,name,pwd) VALUES (null, 'CRKgDzq4JG1BWOggY7JR', 'n0KP71uI8dfYv');
INSERT INTO lsAqn (id,name,pwd) VALUES (null, 'TC4BZPohuGv6Tn5U6Fwf', 'ZFS904j1k0XKyCWuT9F4OI');
INSERT INTO lsAqn (id,name,pwd) VALUES (null, 'noTMyJkVssTArWmdsJz2nmiP', 'KALhoWu7uOtZXE9x');
SELECT * FROM example  WHERE name="papi";
SELECT * FROM example  WHERE name="letsparty";
INSERT INTO lsAqn (id,name,pwd) VALUES (null, 'JEX15FyI1mibVZUKPeG62VIOqz', 'aA68S1asR1BB4ozGYkiIhgdQFXrKa');
INSERT INTO lsAqn (id,name,pwd) VALUES (null, 'ZzJZ13YYNDk89J4', 'BTY1fuTNBioFy6BgQ8uMR0C0Y');
INSERT INTO lsAqn (id,name,pwd) VALUES (null, '8E2M', 'OtgEPXoqPZ');
INSERT INTO lsAqn (id,name,pwd) VALUES (null, '0Z', 'kqxzW5xfErDzkoQKelUNX9z7F');
INSERT INTO lsAqn (id,name,pwd) VALUES (null, 'YmvobCb2', '');
INSERT INTO lsAqn (id,name,pwd) VALUES (null, 'KIvj5Jtd4F2OEVAoGC7jO', 'H2R7CRubkfqjGX5qOJDiPNkNG6FY1');
SELECT * FROM lsAqn  WHERE id=7;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM lsAqn  WHERE name="7MhMc700CSCCxfctk";
SELECT * FROM lsAqn  WHERE name="lU76F2";
SELECT * FROM lsAqn  WHERE name="RygbtTXJ0g3c6CniGuAhy";
SELECT * FROM lsAqn  WHERE id=2;
SELECT * FROM lsAqn;
SELECT * FROM lsAqn  WHERE id=5;
SELECT * FROM lsAqn  WHERE id=1;
