use db;
CREATE TABLE yVFTK (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO yVFTK (id,name,pwd) VALUES (null, 'cIhL44kbhx1a33gVYzPhPDVbSWYef', 'o0EXrdKLIBbyXVnVgs');
INSERT INTO yVFTK (id,name,pwd) VALUES (null, '3X4OWosPIlR3eGL1Xs', '2VFKQtfeBegvfyMl');
SELECT * FROM example  WHERE name="DlbW8RVR";
SELECT * FROM example  WHERE name="cathy3333";
INSERT INTO yVFTK (id,name,pwd) VALUES (null, 'QsYM11NvhpRVp8GTc5fXWH85rJn', 'CJbJhXLXw');
INSERT INTO yVFTK (id,name,pwd) VALUES (null, 'EwgcD5ASq9NheqVckfAvBNI', 'reL6XSbGF40r44sG');
INSERT INTO yVFTK (id,name,pwd) VALUES (null, 'aYi8hp6234k', 'TAWKQWsacE1j3ftEA7');
SELECT * FROM example  WHERE name="faker";
SELECT * FROM example  WHERE name="lemonpie";
INSERT INTO yVFTK (id,name,pwd) VALUES (null, '', 'a7rxZRf3Dk');
SELECT * FROM example  WHERE id=3;
SELECT * FROM example  WHERE id=11;
INSERT INTO yVFTK (id,name,pwd) VALUES (null, '2nbCmTvdfNVnSSdvIg', 'LEFyIWyzSrUhUFKikue9e4s1kGD');
INSERT INTO yVFTK (id,name,pwd) VALUES (null, '9TWOSFL8f7L1C49pEXGocde', 'E4XohtX');
INSERT INTO yVFTK (id,name,pwd) VALUES (null, '4', 'Gp');
SELECT * FROM example  WHERE name="alice1234";
INSERT INTO yVFTK (id,name,pwd) VALUES (null, 'TBy6HF4Fn2obps5SCjtBVHw', 'xeAkcttfrTXIGIlKwZbwPc');
INSERT INTO yVFTK (id,name,pwd) VALUES (null, 'gx4MH3p4czIyf', 'ORhK5reojLiDtUWrrC8vIGehC9eIL');
INSERT INTO yVFTK (id,name,pwd) VALUES (null, 'tYq3QgLLi', '6NALUkEn4Vg');
SELECT * FROM example  WHERE name="nllDHE1vDah1Ql0IhQAl";
SELECT * FROM example  WHERE name="WY38OLp4JY9V1i5PDNPvPmov";
INSERT INTO yVFTK (id,name,pwd) VALUES (null, 'yImkuj4A2U0ZRfTC4UF2', 'XXWyZZU');
INSERT INTO yVFTK (id,name,pwd) VALUES (null, 'rMEdoGpMxenFdCC', '47LYGm7KEoS3o');
INSERT INTO yVFTK (id,name,pwd) VALUES (null, 'oWH9NwEZuDOEmNxrxkI53CJ7eteFe', 'rOu');
SELECT * FROM yVFTK  WHERE id=10;
SELECT * FROM yVFTK;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM yVFTK  WHERE id=14;
SELECT * FROM yVFTK  WHERE name="gJsIhld0n";
SELECT * FROM yVFTK  WHERE id=0;
SELECT * FROM yVFTK  WHERE name="HfIIPX7KN6Qo2HzZtzXFSBL";
