use db;
CREATE TABLE RdASP (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'ED7SarrR9ZxoWzDFqpUyt', 'BVl6V000pMRnNLafBs');
SELECT * FROM example  WHERE name="hollywood36830";
SELECT * FROM example  WHERE name="hoVWjHaKoogeP3E";
INSERT INTO RdASP (id,name,pwd) VALUES (null, '77LERfTMeD', 'FdZtnArF1HrUrjar');
SELECT * FROM example  WHERE name="cAPDWFpu6VxrIVRk";
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'S', 'ZmY5MUJf');
SELECT * FROM example  WHERE name="cathy3333";
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'wWMe09PikkTrDxd', 'C2YvfaiC66VxRr8hiv5');
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'NFUgYqEBiOKoSs6', 'lrg8JXN0N7');
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'U6LQmv1oGigeB', 'AFXKoF1R4lp20');
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'h2eknu4', 'imwdc5ejdTKzcmNdiz7pF');
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'akdhXZ9lIeafSnqpWKiIaayz0L', 'faOals21gUzcl6');
SELECT * FROM example  WHERE name="o3ToZKZrb";
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'Cy', 'x4TocUh9qUgiIMV80');
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'Lc', 'lAQBJHjMvc9sWdO');
SELECT * FROM example  WHERE id=5;
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'exTgosBcsSJ0WJ0a0D1sy4QbJ', 'ZKIqfOMATowRzxt0k7');
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'bPmHGR', 'BXxaGQUNrkuEVDpUbT');
SELECT * FROM RdASP;
INSERT INTO RdASP (id,name,pwd) VALUES (null, 'KiVMgr', 'xpWtb5YXu');
SELECT * FROM RdASP  WHERE name="uc5J2KyPhMdM2bHEC";
SELECT * FROM RdASP  WHERE name="MunxuQA80T5t7tD";
