use db;
CREATE TABLE nkoXo (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="xeoncpu";
SELECT * FROM example  WHERE name="varus";
INSERT INTO nkoXo (id,name,pwd) VALUES (null, '', 'EpowvsB');
INSERT INTO nkoXo (id,name,pwd) VALUES (null, 'deN', 'R8H8');
SELECT * FROM example  WHERE id=15;
SELECT * FROM example  WHERE id=16;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE name="Dr.Umphress";
SELECT * FROM example  WHERE name="mcdonalds";
INSERT INTO nkoXo (id,name,pwd) VALUES (null, 'akjvmuoaDK6fgfDEI', 'xl');
INSERT INTO nkoXo (id,name,pwd) VALUES (null, 'QS4ZzCZXm2', 'lLTuHn2Vk0pvMqHXemsbCE');
SELECT * FROM nkoXo;
SELECT * FROM example  WHERE id=4;
SELECT * FROM example  WHERE id=16;
SELECT * FROM nkoXo  WHERE id=2;
SELECT * FROM nkoXo  WHERE name="yYuaoYWgdxk6ELUw";
SELECT * FROM nkoXo  WHERE name="lN208pGXnWuL0CvAiemMwKF1Z";
