use db;
CREATE TABLE HUByx (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO HUByx (id,name,pwd) VALUES (null, 'KGjgObJnSiUSNrVLLqE9', '7D');
SELECT * FROM example  WHERE name="faker";
SELECT * FROM example  WHERE name="2AJUInWw";
INSERT INTO HUByx (id,name,pwd) VALUES (null, '7OXSVV', 'ZpUK6xZHsheYV1YQVVzeIxQE');
INSERT INTO HUByx (id,name,pwd) VALUES (null, '3IU5JHGP3hVi4kLGvB4', 'ASykIbyd4QkDCu');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO HUByx (id,name,pwd) VALUES (null, 'uXvCYV', '5Lh');
INSERT INTO HUByx (id,name,pwd) VALUES (null, 'GWxv', '9knxXYnWLpAx1GiZNYDw');
SELECT * FROM HUByx;
INSERT INTO HUByx (id,name,pwd) VALUES (null, 'p3d876sC70SjlVtDcb', '0ttfP');
SELECT * FROM example  WHERE name="singular";
INSERT INTO HUByx (id,name,pwd) VALUES (null, 'vXM05Q9PKRyGhgaFutk6G5gmKEY', 'yrOEGZWulRJm');
SELECT * FROM example  WHERE name="queenofthrone";
INSERT INTO HUByx (id,name,pwd) VALUES (null, 'MMPAnPfL21j7w', 'sEAp24W4N53S8Ghk3jaKIKAOhLAm');
INSERT INTO HUByx (id,name,pwd) VALUES (null, '9RAlaE1hCOYOHunkRq1Agfec', 'PUYoqAbkuQF3bkM');
INSERT INTO HUByx (id,name,pwd) VALUES (null, 'JNceGKlWFgZH', 'jx6IAIFrqGtiYodm7u2TKJ7NsqWyB');
INSERT INTO HUByx (id,name,pwd) VALUES (null, '453dYGn6QWVgv', 'Q9gJYOgwKb0hqjPmaNeuZjPDDyvz');
INSERT INTO HUByx (id,name,pwd) VALUES (null, 'rEnqapEzdXyER1zhvm3K', 'xfBps');
INSERT INTO HUByx (id,name,pwd) VALUES (null, 'LRC55BkgrPVMIVUOjMBLnp4', 'bDntYvxehuaTJJcbtGC8g');
SELECT * FROM HUByx  WHERE name="Hiq0DzEXWtvAN";
SELECT * FROM HUByx  WHERE name="KrdgWb";
SELECT * FROM HUByx  WHERE name="qA2CSkXvfQXJtuj";
SELECT * FROM HUByx  WHERE name="U";
