use db;
CREATE TABLE NYkSL (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE id=14;
INSERT INTO NYkSL (id,name,pwd) VALUES (null, '9vhxE5puUgTccXS', 'RDj3lOEuttyR3');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'JgvRIDXu3ZbPy2Qle0cxJ9ut42tCX', '4Ea7LmD51Pso0vDdl');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'Icb86bWMUkwuT', 'k2DdsQiz77n1aEzg');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'P', 'd');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'lvS67AmmloVc54Bo2JtE1', '3pjI');
SELECT * FROM NYkSL;
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'erCM5alC', 'NU6mirvz8RK8fJLp8v1qxmgIpClX');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'bYfl', '87hQ9A');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'xC', 'GAfxMM1Xti0WQQfP6R9xVeUdiN4');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'WXifLEA', 'u4FOolVpsqmMBkCK1oV84viDJt');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'PIcHhkXJl4', '259Is');
SELECT * FROM example  WHERE name="oppo";
SELECT * FROM example  WHERE id=0;
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'rkzCeYgaev9tNTpA', 'N');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'Dtbo2xvE378b9fqD8HjdnebVZ', 'G');
SELECT * FROM example  WHERE id=12;
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'btXS31l', 'TtpEMbDnuady94g7sn');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'Q3KZvZCTq', 'eYDC3wu');
SELECT * FROM example  WHERE name="xrayfighter";
INSERT INTO NYkSL (id,name,pwd) VALUES (null, '42PwdAl8W41Nf2PJbkkE8RS', 'LzQWh');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'sGUZj2xomyslVLBQQeU2PTlFvoXN', 'pMtvriHTi');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'Q1SOy30', 'GnU');
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'jUZhVBbRzBjvg56kJ5L55M1Pib', 'rj6my');
SELECT * FROM example  WHERE name="eg6R2celWYpINJC02Gc1dKa3";
INSERT INTO NYkSL (id,name,pwd) VALUES (null, 'nozL4V0cHm', 'gCLsNU9G');
SELECT * FROM NYkSL  WHERE name="2NaCmuCobtV0OvyIXbFpoKj";
SELECT * FROM NYkSL  WHERE name="7Hg6RvivKiSVZ";
SELECT * FROM NYkSL  WHERE name="4675hQ8VQauXfzVfhokSzpI";
SELECT * FROM NYkSL  WHERE name="hfu3VZX6yFd38SCU";
SELECT * FROM NYkSL  WHERE id=7;
SELECT * FROM NYkSL  WHERE id=18;
SELECT * FROM NYkSL  WHERE id=19;
