use db;
CREATE TABLE TVSgK (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO TVSgK (id,name,pwd) VALUES (null, 'YZlm3m4eKcThrXkSC8xVpx8f32', '6l0LW7pXWdSLEaG73pBoB517Czj3');
INSERT INTO TVSgK (id,name,pwd) VALUES (null, 'qgCCExko4swOXTOqbfiNnnlaw4j6', 'PNKFoWtEJMzwj');
SELECT * FROM example  WHERE id=11;
INSERT INTO TVSgK (id,name,pwd) VALUES (null, '2fCwzvmJ8', 'w3MqdtwTv1nypK5Ml2NrCF');
SELECT * FROM example  WHERE id=4;
INSERT INTO TVSgK (id,name,pwd) VALUES (null, 'XX7', 'O8X');
INSERT INTO TVSgK (id,name,pwd) VALUES (null, 'jJZ8', '1ATE1Jq8ecpIcFLF7INcTcYC');
SELECT * FROM example  WHERE name="papi";
INSERT INTO TVSgK (id,name,pwd) VALUES (null, 'fEO8lyw2qGKLTPusO', 'hSSlWPTVfwxxekrQz9b');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO TVSgK (id,name,pwd) VALUES (null, '1waNkoL', '0m');
SELECT * FROM TVSgK;
SELECT * FROM example  WHERE id=17;
SELECT * FROM TVSgK  WHERE name="G6mFZ";
SELECT * FROM TVSgK  WHERE id=7;
SELECT * FROM TVSgK  WHERE id=7;
SELECT * FROM TVSgK  WHERE name="Z8oCr9FifcRGC3tOdysirRNfz";
SELECT * FROM TVSgK  WHERE id=4;
SELECT * FROM TVSgK  WHERE name="b9uMIPP4T";
