use db;
CREATE TABLE MnTlo (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO MnTlo (id,name,pwd) VALUES (null, 'qHwqmiKA1335czObYrEHMEvtPSRSp', 'J7vMcILw2BqDvygcHR27k3x4xC');
INSERT INTO MnTlo (id,name,pwd) VALUES (null, '3u1glZJFQPfWWb993XnwF', '4F1C5');
SELECT * FROM example  WHERE id=12;
SELECT * FROM example  WHERE name="LF34p5K9AQbBr6NWzcZ";
SELECT * FROM example  WHERE name="CMf9RlbNkVQ2F";
INSERT INTO MnTlo (id,name,pwd) VALUES (null, 'yEXgmsHveFiia', 'aKTiYRvgxKbOTisSnDSA');
INSERT INTO MnTlo (id,name,pwd) VALUES (null, 'PkrDLvoRikCw64qLg1N4', 'ArMJtWI');
SELECT * FROM example  WHERE name="O5yqPfo";
INSERT INTO MnTlo (id,name,pwd) VALUES (null, 'rwJrwkngxBU', 'Wp');
INSERT INTO MnTlo (id,name,pwd) VALUES (null, '4D', 'aLU4fpLDQszU0ieAqCtIqeSFik');
INSERT INTO MnTlo (id,name,pwd) VALUES (null, 'Dk9vlJjJQpUBMFHWIm41pTtGOf', 'jR4Bp');
SELECT * FROM example  WHERE name="killerleon";
SELECT * FROM example  WHERE name="S56oYDKUv";
SELECT * FROM MnTlo  WHERE name="9DXH8YoSHkprMS8o7eheoAtAD";
SELECT * FROM MnTlo  WHERE name="";
SELECT * FROM MnTlo  WHERE name="6Pdlevacmy5c8QS5tKOkjdEoa";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM MnTlo  WHERE id=3;
SELECT * FROM MnTlo;
