use db;
CREATE TABLE RtVWX (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM RtVWX;
SELECT * FROM example  WHERE name="AZqgpDnPUQYhqUulKHw";
SELECT * FROM example  WHERE id=15;
SELECT * FROM example  WHERE name="pt6N6VU3XjK";
SELECT * FROM example  WHERE id=0;
SELECT * FROM example  WHERE name="Dr.Umphress";
SELECT * FROM example  WHERE name="waveyourhand";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE name="q";
SELECT * FROM example  WHERE name="restinpeace";
SELECT * FROM RtVWX  WHERE id=0;
SELECT * FROM RtVWX  WHERE name="II37nwmuneZzMyt";
SELECT * FROM RtVWX  WHERE id=0;
SELECT * FROM RtVWX  WHERE name="LfUMFbAtnB";
SELECT * FROM RtVWX  WHERE id=0;
SELECT * FROM RtVWX  WHERE id=0;
SELECT * FROM RtVWX  WHERE name="JYh6C12Ud06WlmCxJLk0TJEb9bzu";
