use db;
CREATE TABLE DlnWJ (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, '9XtzRiPgs', 'S51StiGKKNrGj9J9w');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'vC7ssctV', '8beDaB35eKYgtRSSw');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'YUXbXHl4NjAphKXvmVQvTnfT6v', 'q6PbjMfURKp9zmroCRD7OBh9gbB8n');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'TrSHco2xEe8F1', 'gIw96zNpAbov');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'XztMBhJLAIrK7omoc', '40P8TVo0P');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'Xm2DmguNWPgG7LwjviFfBzaQBt7g9', 'g0CIVsczRctj5O');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'Bnak3Ac', 'uvLVU7AKM1VzALYfD4sY');
SELECT * FROM example  WHERE name="verus";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'yvT62JdsIaF9q5', 'Ql4zZeJZYY8jw');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'sUX4jr0nfreBpSXg15', 'jKxuAeEhCP3IVRnj84W9T3');
SELECT * FROM example  WHERE id=7;
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'pz2Jf8zggK0kh5', 'uA');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'YvioR73Tnh69M21', 'I8U4g1TiGVKTOI6sPpZuyJqoUeEFV');
SELECT * FROM DlnWJ;
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'Qz8q3HzKcK', 'G6pOFziqQwlDm2murSLF2Ok');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'jmc2e7', 'qFMa32Y6GutkbgU');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'IAn3YcE9R1metNWFCv', '');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'GoUBhk', 'ihGTLxBNZzP');
SELECT * FROM example  WHERE name="WLLrrfHga7Ojv3YF2RvG9slRlsriX";
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'iEMhrAQVjB3Qq', 'HxmpSkRte1vOjm0yn7tV2OqT');
INSERT INTO DlnWJ (id,name,pwd) VALUES (null, 'IhpR1S9YZgLFRaI', 'cliVx6wKhKRDu');
SELECT * FROM example  WHERE name="nTJzuygyVAAVR6cyWkY7jX71DpqMJ";
SELECT * FROM DlnWJ  WHERE id=7;
SELECT * FROM DlnWJ  WHERE name="3R";
SELECT * FROM DlnWJ  WHERE id=7;
SELECT * FROM DlnWJ  WHERE name="KOPWc";
