use db;
CREATE TABLE cqstG (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE id=7;
INSERT INTO cqstG (id,name,pwd) VALUES (null, 'TmuAsMbgJl', 'wcSbybYLSWF2O0bG');
SELECT * FROM example  WHERE name="3M2Lf";
SELECT * FROM example  WHERE id=2;
INSERT INTO cqstG (id,name,pwd) VALUES (null, 'Ww3iz6BanZgg', 'J');
SELECT * FROM example  WHERE id=6;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM cqstG;
INSERT INTO cqstG (id,name,pwd) VALUES (null, 'sBvzmXuwETRoS07KFe', 'x1hY8zHRrrJfRu4ImPId5Xb');
SELECT * FROM example  WHERE name="cathy3333";
SELECT * FROM cqstG  WHERE name="g8";
SELECT * FROM cqstG  WHERE name="tfkT9LEllZsaCwKRL84x3UXw";
SELECT * FROM cqstG  WHERE id=1;
SELECT * FROM cqstG  WHERE name="jdojB8wJ";
SELECT * FROM cqstG  WHERE name="rKoKheV3u9G5YVZSzgCyRzioqG";
SELECT * FROM cqstG  WHERE id=3;
SELECT * FROM cqstG  WHERE id=1;
