use db;
CREATE TABLE mwpBu (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM mwpBu;
SELECT * FROM example  WHERE name="YM8J";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE name="IzajfpqcY97FuvYux9vvuLeb1Mij";
INSERT INTO mwpBu (id,name,pwd) VALUES (null, '6OTWBKhbfDkMHeHeyJII', 'YAsxcxpVUUCgJyUXyPw6Tx53agY3');
SELECT * FROM example  WHERE name="italy1912";
SELECT * FROM example  WHERE id=15;
SELECT * FROM example  WHERE name="bob!!!";
INSERT INTO mwpBu (id,name,pwd) VALUES (null, '1r', 'y8KMwNd3');
SELECT * FROM example  WHERE name="verus";
SELECT * FROM example  WHERE name="DpqG5gcWCHY";
INSERT INTO mwpBu (id,name,pwd) VALUES (null, 'vdMCmJtf2Uflun1RZLRxUC0Uhka', '06V94lBwjGdxq2JobGM');
SELECT * FROM example  WHERE name="xVrXVEJbb";
SELECT * FROM mwpBu  WHERE id=2;
SELECT * FROM mwpBu  WHERE id=1;
SELECT * FROM mwpBu  WHERE id=0;
SELECT * FROM mwpBu  WHERE id=0;
