use db;
CREATE TABLE knBwO (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE id=11;
INSERT INTO knBwO (id,name,pwd) VALUES (null, 'nH86QCgQQu1O1Uz6rJojM', 'v4vnClzlgW4');
INSERT INTO knBwO (id,name,pwd) VALUES (null, 'aF1hdpyIpHPHE', 'Q5K5wwtF7UYY');
SELECT * FROM example  WHERE name="joke";
INSERT INTO knBwO (id,name,pwd) VALUES (null, '5eJEjV9eLr9MA7UiRBvMH2wZ', 'uC3gGX9FW0mkjsNlQN9');
SELECT * FROM example  WHERE name="euro";
INSERT INTO knBwO (id,name,pwd) VALUES (null, 'PdTAAHsJ', '0bSOjtFIAaHBoBfTa96EDacQKvZ');
SELECT * FROM example  WHERE id=8;
INSERT INTO knBwO (id,name,pwd) VALUES (null, 'Q', 'IhrIlMV7mJpJb4');
INSERT INTO knBwO (id,name,pwd) VALUES (null, 'Jq5ePIwbomZgj9QRABe', 'aDCoGwa3XCcK23fmHZ5Ke');
INSERT INTO knBwO (id,name,pwd) VALUES (null, 'OeLP78S2E', 'wA8jz1DTyZCmQbC6db2SA');
INSERT INTO knBwO (id,name,pwd) VALUES (null, '96zXZibYD', 'f3vHGEXh8mdaFd4');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO knBwO (id,name,pwd) VALUES (null, 'UE00tRCWhRNoCYIchcl7zu', '');
SELECT * FROM knBwO;
INSERT INTO knBwO (id,name,pwd) VALUES (null, 'SlvvY1QYGyu', '5aIaTCBOPbSXdnz9q9');
INSERT INTO knBwO (id,name,pwd) VALUES (null, 'yJ0', 'cAeeNTrWEUDsgET');
INSERT INTO knBwO (id,name,pwd) VALUES (null, 'kxN3DfwedGXS3OMYf13BQRdH', 'hOqUrBUAdOTo0tmgcmQX');
SELECT * FROM example  WHERE id=1;
SELECT * FROM knBwO  WHERE name="Mn8jhjFWA";
SELECT * FROM knBwO  WHERE id=7;
SELECT * FROM knBwO  WHERE id=3;
