use db;
CREATE TABLE dOFsD (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="cici1001";
INSERT INTO dOFsD (id,name,pwd) VALUES (null, 'mCWnSc87ufWsi', 'Ymd77al9F');
SELECT * FROM dOFsD;
INSERT INTO dOFsD (id,name,pwd) VALUES (null, 'eDNUWvjAXvhmyU', 'Lf8z');
SELECT * FROM example  WHERE name="J0qdj";
SELECT * FROM example  WHERE name="oppo";
INSERT INTO dOFsD (id,name,pwd) VALUES (null, '5LNxGajELDSOjEGw5Bz', 'miWPzmEJBxDUHLJcEoFU');
SELECT * FROM example  WHERE name="tEt";
INSERT INTO dOFsD (id,name,pwd) VALUES (null, '77UDeF7nyPy4DVfSqBd2', '1kheuKJZdi0gg7SsmVG9');
INSERT INTO dOFsD (id,name,pwd) VALUES (null, '8IJlU8WHUgK', 'vggYITvHt');
INSERT INTO dOFsD (id,name,pwd) VALUES (null, '589Lb', 'edunliurLkHB');
SELECT * FROM example  WHERE name="XbULB6nUL59Yr0uOl";
INSERT INTO dOFsD (id,name,pwd) VALUES (null, '7aNu6F8DhJ4My04mj', 'ehp78pte8eH');
INSERT INTO dOFsD (id,name,pwd) VALUES (null, 'RFK94pwIoYHE0', '9b8Z05EIRzmDvqi');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO dOFsD (id,name,pwd) VALUES (null, '3PxIrHJCTS2PBvSui6235HWP8h5e', 'uNK7v8rbKM3lvPvlN');
SELECT * FROM example  WHERE name="";
SELECT * FROM dOFsD  WHERE id=4;
SELECT * FROM dOFsD  WHERE id=7;
SELECT * FROM dOFsD  WHERE id=8;
