use db;
CREATE TABLE AWXeV (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'jZLAvEQxpu1RJIeAb7vXvyhnmo74', 'amrYY17KvOyvnCliSksV');
SELECT * FROM example  WHERE name="orthogonal";
SELECT * FROM example  WHERE name="TIh5UV0daQqFi4F9R6Ps";
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'ryMULFfRYty95HZI8vk0GgU', 'h05dSTJrP');
SELECT * FROM example  WHERE name="2hzHjHKi3JJ9uqh9FA";
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'qTTSfgdqIGo1a6a2w7gWa3', 'qcqENg');
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'YmcJ', 'HJPMuh5UM2diTJIbgez0oOivXe');
SELECT * FROM example  WHERE name="RPGyZPRwNCDKG4FX";
SELECT * FROM example  WHERE id=7;
SELECT * FROM example  WHERE name="yougurttastesgood";
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'IU', '3CI7qb1ER');
SELECT * FROM example  WHERE name="Dr.Umphress";
SELECT * FROM example  WHERE id=18;
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'Fj7yOeE53', '7JbfpMn4y2pZR53dr7n1fiGGxGpT');
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'GnP40FkPslyJi', '2OwxooRytHT6G86KiTFYDt0yW');
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'c0g1swnTnWEX', '3bERI1uKRYnV72i');
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'FPsctjFYPqMOGZiPs515RPZsL8BQB', 'QWPtvoiQmnEiOIL8xwcV49FAi');
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'GqmSKhdqbYH', 'xFJq');
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'NeBLivPPFFJTr8ys46CGkbwd0r2', 'FUw0');
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'B5iK7PbXOWWiTda0Y3MmK5sHPv', 'mTxJNqX574w5WwVV043X3INtDY');
INSERT INTO AWXeV (id,name,pwd) VALUES (null, 'n', '');
SELECT * FROM AWXeV  WHERE id=8;
SELECT * FROM AWXeV  WHERE id=9;
SELECT * FROM AWXeV  WHERE name="";
SELECT * FROM AWXeV  WHERE id=2;
SELECT * FROM AWXeV  WHERE name="ezGjp";
SELECT * FROM AWXeV;
SELECT * FROM AWXeV  WHERE name="foGX1vr8cJObL80NzhnbJO8";
SELECT * FROM AWXeV  WHERE id=11;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
