use db;
CREATE TABLE qDPEb (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE id=0;
SELECT * FROM example  WHERE id=1;
SELECT * FROM example  WHERE id=16;
SELECT * FROM example  WHERE name="A8bu5fmVk9Iy";
INSERT INTO qDPEb (id,name,pwd) VALUES (null, 'A94xndI0nzYJwVMWR1suvW9m', 'OQwv');
INSERT INTO qDPEb (id,name,pwd) VALUES (null, 'hCKG', '');
SELECT * FROM example  WHERE name="k0WT4KAgZR4GWQMtwJpDbYLBa36";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE name="restinpeace";
SELECT * FROM example  WHERE name="zookeeper001";
INSERT INTO qDPEb (id,name,pwd) VALUES (null, 'NEtoACDbmTuNifnRsTTRz4Nwx', 'nTtLtzIPYNvTLHwpbOQYqd');
SELECT * FROM example  WHERE name="2YaDdQ9wK";
SELECT * FROM qDPEb;
SELECT * FROM example  WHERE id=1;
SELECT * FROM example  WHERE name="GcqPx74tiaakJtKF26jaYe";
SELECT * FROM qDPEb  WHERE id=1;
SELECT * FROM qDPEb  WHERE id=2;
