use db;
CREATE TABLE InbKC (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO InbKC (id,name,pwd) VALUES (null, '4QSmwrj6', 'vOIRhyXeyjVJjMaQeaMVtMEiPrQP');
SELECT * FROM example  WHERE name="duck233";
INSERT INTO InbKC (id,name,pwd) VALUES (null, 'f', 'Fn5Pe3bIs3A');
SELECT * FROM example  WHERE id=8;
INSERT INTO InbKC (id,name,pwd) VALUES (null, 'upCjwz9Mm', 'bXEWtBTUR5E690sFgGut');
SELECT * FROM example  WHERE name="TBG4uWm16k0fdO1v5sKgmJRoLqVh";
INSERT INTO InbKC (id,name,pwd) VALUES (null, '', 'bkJb');
INSERT INTO InbKC (id,name,pwd) VALUES (null, '5fhhp1WANv9PpIrBR', 'ZJv1LolkWFU7nTRWoq');
SELECT * FROM example  WHERE id=13;
INSERT INTO InbKC (id,name,pwd) VALUES (null, 'Fhe', 'mQ1qpxCuRY8fGwGDp7U');
INSERT INTO InbKC (id,name,pwd) VALUES (null, 'jDwBN', '46dGTd3CDvsaIsll');
INSERT INTO InbKC (id,name,pwd) VALUES (null, 'V3e0rgx', '8T');
INSERT INTO InbKC (id,name,pwd) VALUES (null, 'g71Cg7', 'ryhWkD2PEQnR6frq5NCMHLHA6n0');
INSERT INTO InbKC (id,name,pwd) VALUES (null, 'WfC', 'k8h5CgKo');
INSERT INTO InbKC (id,name,pwd) VALUES (null, 'RitW9fGNOqZGVPHedLU', 'Z5LnE2CRZBbKT');
SELECT * FROM example  WHERE name="waveyourhand";
SELECT * FROM example  WHERE name="tt1pwk0mm";
INSERT INTO InbKC (id,name,pwd) VALUES (null, 'Cc4IGhgsYIadLLWDV', '91Qk2TrqZZBDofNMSEPJm');
SELECT * FROM example  WHERE name="bake222";
INSERT INTO InbKC (id,name,pwd) VALUES (null, '', '2jHXiljSnTohFsbnx');
SELECT * FROM example  WHERE name="O";
SELECT * FROM example  WHERE id=13;
INSERT INTO InbKC (id,name,pwd) VALUES (null, 'rupILE', 'pZphYB38JV');
SELECT * FROM example  WHERE name="0ln4TM03WDG8w5ovsNvvy9gMV";
SELECT * FROM InbKC  WHERE id=8;
SELECT * FROM InbKC;
SELECT * FROM InbKC  WHERE name="5EODrTgeKM";
SELECT * FROM InbKC  WHERE name="SmVZadhEyPuyZuQ";
SELECT * FROM InbKC  WHERE name="vG";
SELECT * FROM InbKC  WHERE id=13;
SELECT * FROM InbKC  WHERE id=3;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM InbKC  WHERE id=11;
