use db;
CREATE TABLE mFMmr (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 'gMXwom9tYVEj4Gc', 'q8m3fZ1tWQslT1WJO2r');
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 'R', '3UTNGVGHTum');
INSERT INTO mFMmr (id,name,pwd) VALUES (null, '8RMaZxtQRCDnqruW2n3', '58AbU5cayg54KTz4irsp59YyU');
SELECT * FROM example  WHERE name="faker";
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 'nRdZEHhk1o6Gbf', 'cwb1p542ALXcdigLWLyUCKJvn0DS6');
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 's8i7f79MvAR7m8', 'cDtA');
SELECT * FROM example  WHERE id=6;
SELECT * FROM mFMmr;
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 'bkixa', 'ul5K1UByEwKf');
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 'DHrRHcdOFG', 'LtHoAGVckCDidsGbMj');
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 'WdWlpfDd', 'QW3eMtN28DWYJm74gn5JV7sZauAR');
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 'xFGRwSfXnTI4XJWJ7yvqMenuwQ', 'mlCN7u1DABAG9E5CGJf0');
SELECT * FROM example  WHERE name="killerleon";
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 'ARw7lVPeoEnUtz6', 'GIxHjVDrawtwjQBMr');
SELECT * FROM example  WHERE id=4;
SELECT * FROM example  WHERE id=10;
INSERT INTO mFMmr (id,name,pwd) VALUES (null, '3TiDb6EvFIupg0aD2rTQ', 'GPdhyd3HRq');
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 'f', 'Fh3uwpmd');
INSERT INTO mFMmr (id,name,pwd) VALUES (null, 'uFjXek6Lkqh', 'P8r0J7qNoZMGlK4gnWiEmxNUhs1XT');
SELECT * FROM mFMmr  WHERE id=7;
SELECT * FROM mFMmr  WHERE name="bVFmBEpJjsjb";
SELECT * FROM mFMmr  WHERE name="B3";
SELECT * FROM mFMmr  WHERE id=1;
SELECT * FROM mFMmr  WHERE id=7;
