use db;
CREATE TABLE tgRcB (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO tgRcB (id,name,pwd) VALUES (null, 'ey23tQkCxtfS9uyvFyEJtxk', 'cV');
INSERT INTO tgRcB (id,name,pwd) VALUES (null, 'l4cR9b', 'ZF51hcDYRzXHuO8aoBwxjlRZcn');
SELECT * FROM example  WHERE id=14;
INSERT INTO tgRcB (id,name,pwd) VALUES (null, 'AMG3g6Bhu0Z4', 'kBKss4NvGS');
INSERT INTO tgRcB (id,name,pwd) VALUES (null, 'aqasz', '64WGzY5YnMBRAT6c8tHoOXevnqaH');
INSERT INTO tgRcB (id,name,pwd) VALUES (null, 'Ld5GPRG5HfFwR', 'dZfDKctXCNIF6WDE');
INSERT INTO tgRcB (id,name,pwd) VALUES (null, 'PKJAIYxIx', 'tGHpsFmaR2smC');
INSERT INTO tgRcB (id,name,pwd) VALUES (null, 'JRk7kst6C', 'Qekw4mKE9DDV00k327H9QM8xx9aL');
SELECT * FROM example  WHERE id=11;
INSERT INTO tgRcB (id,name,pwd) VALUES (null, '6FKdVcPxygV5v6C3tASR', '1xmGFZXw4yLpA0VclW5zGl3wQSKy9');
INSERT INTO tgRcB (id,name,pwd) VALUES (null, '1c5TvlJAehTDX', 'd0');
SELECT * FROM example  WHERE name="l";
INSERT INTO tgRcB (id,name,pwd) VALUES (null, '4tzjm4YMMqLxFhkbScumpI', 'ozolra0rSCiTnM1ACZN4n4');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO tgRcB (id,name,pwd) VALUES (null, 'jhSVPP8cUVH76KFJ5k', 'NW3igTApdL8QJZ5');
SELECT * FROM tgRcB;
INSERT INTO tgRcB (id,name,pwd) VALUES (null, '9D', 'qUebKUX2hzH7bhZnWBahsLTEfJojg');
SELECT * FROM example  WHERE name="iuK9ahHq";
SELECT * FROM tgRcB  WHERE name="uIlgalA8meTpSLo45mHTKARcA";
SELECT * FROM tgRcB  WHERE name="";
SELECT * FROM tgRcB  WHERE name="D5YpBHAVbK69qeEqYGMoqa1IT9xnR";
SELECT * FROM tgRcB  WHERE name="4IbVASl";
