use db;
CREATE TABLE wjGWh (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO wjGWh (id,name,pwd) VALUES (null, 'duWrbiJujxri6IaI5hiQvL', 'v9I4DivJl8qhXobe');
SELECT * FROM example  WHERE name="2kY2kZOaJ";
INSERT INTO wjGWh (id,name,pwd) VALUES (null, 'BCNSphfiuq', 'QaFvk1iAn0');
SELECT * FROM example  WHERE name="aCt3hqGnjeW4jm";
INSERT INTO wjGWh (id,name,pwd) VALUES (null, 'Q4tj2f7kANAAq1VcHbMRZ', 'WJD8YBJ');
SELECT * FROM example  WHERE id=10;
INSERT INTO wjGWh (id,name,pwd) VALUES (null, 'O9BMIvprRGtEp0DTg', 'GVDPS7oCPDkqROg66');
SELECT * FROM example  WHERE id=9;
INSERT INTO wjGWh (id,name,pwd) VALUES (null, 'dEkFIPG5dwb4Nr63IBxFOBdYz2G6s', 'uJO0mzSYEgShjoJMu365ZoY5gJwl');
INSERT INTO wjGWh (id,name,pwd) VALUES (null, 'xTM4aSqFn6RCbN8JCf', 'If20BzkFpcnJmDcz0cUn');
INSERT INTO wjGWh (id,name,pwd) VALUES (null, 'DXAw6wtWyQ8wJk', 'Ed2ebrnAH');
SELECT * FROM example  WHERE name="gaga";
SELECT * FROM example  WHERE name="brmm3FczNcnLVYeLm0XHw6C";
SELECT * FROM example  WHERE id=5;
INSERT INTO wjGWh (id,name,pwd) VALUES (null, '8nZy7YhQdgg', 'B1ZiP');
SELECT * FROM example  WHERE name="z";
SELECT * FROM example  WHERE id=19;
SELECT * FROM wjGWh  WHERE name="Qpm";
SELECT * FROM wjGWh;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM wjGWh  WHERE id=0;
