use db;
CREATE TABLE HYvdt (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="gaga";
SELECT * FROM example  WHERE name="killerleon";
SELECT * FROM example  WHERE name="uNIE0rB8oPwOMO";
SELECT * FROM example  WHERE name="zookeeper001";
SELECT * FROM example  WHERE name="1gMzc470Vxy2vcdf7CbC";
SELECT * FROM example  WHERE name="BzZt63j4S12SPzBGUpfhzQ7";
SELECT * FROM example  WHERE name="4OQZov62AJ4uJWq8O1A0dRb6Lsm";
SELECT * FROM example  WHERE name="alice1234";
SELECT * FROM HYvdt  WHERE id=0;
SELECT * FROM HYvdt  WHERE name="ht30PhYXUOBJ3crnfXhgrJ";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM HYvdt  WHERE id=0;
SELECT * FROM HYvdt  WHERE id=0;
SELECT * FROM HYvdt  WHERE name="f2XqOH3";
SELECT * FROM HYvdt  WHERE name="LD81l6X6eu3Y0XAf76b5Tu";
SELECT * FROM HYvdt;
SELECT * FROM HYvdt  WHERE name="";
