use db;
CREATE TABLE spagX (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO spagX (id,name,pwd) VALUES (null, 'tnoTVltX', 'CvajEwE0');
SELECT * FROM example  WHERE name="rHE1px13LkJA1kvTf7";
INSERT INTO spagX (id,name,pwd) VALUES (null, 'nspU9bc9Opwg0RChd', 'qWLO7mjdT5jBT2NO6Hg5k4');
SELECT * FROM example  WHERE id=13;
INSERT INTO spagX (id,name,pwd) VALUES (null, '2XWoPWHl', '6AXciJekd6R1lwb10XPWU');
SELECT * FROM example  WHERE id=16;
SELECT * FROM example  WHERE name="IyQxihH5jLBSg";
INSERT INTO spagX (id,name,pwd) VALUES (null, 'emC33qk5kk1zYfVTMG84', 'L5sqR');
SELECT * FROM example  WHERE name="eMKdWl86myucs1";
INSERT INTO spagX (id,name,pwd) VALUES (null, 'u5w9s7YJk1Y3m', 'rUbWgQed9WSS');
INSERT INTO spagX (id,name,pwd) VALUES (null, 'm', 'TzPrOJz0ywLRpVkl6zo6clR33yXYb');
INSERT INTO spagX (id,name,pwd) VALUES (null, 'hvOWi9cmQHLdS0YbBaLSXYwdr', '1oHrXw');
INSERT INTO spagX (id,name,pwd) VALUES (null, 'Pkf0GUs41y840VLlmh23', 'jM7UP0gkRrjhO2OanB7Bj');
SELECT * FROM spagX  WHERE name="gCEb4TwL8kRRSPOL8PpyBYC1ji3";
SELECT * FROM spagX  WHERE name="gEiMLx0fgJtbWGkw5OWzjnLV";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM spagX  WHERE id=6;
SELECT * FROM spagX;
SELECT * FROM spagX  WHERE name="88qHsdZn";
SELECT * FROM spagX  WHERE id=8;
SELECT * FROM spagX  WHERE id=5;
SELECT * FROM spagX  WHERE name="M2FD";
