use db;
CREATE TABLE qyBPZ (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO qyBPZ (id,name,pwd) VALUES (null, 'rfhBLQ7G37zwo', 'U');
SELECT * FROM example  WHERE name="iterations";
INSERT INTO qyBPZ (id,name,pwd) VALUES (null, 'nTO9U52dlI8bzJTM', 'NNpyfg4rxLbgO5yGiYTSqvlRjElUJ');
INSERT INTO qyBPZ (id,name,pwd) VALUES (null, 'drg2', 'xzAX');
SELECT * FROM example  WHERE name="xrayfighter";
SELECT * FROM example  WHERE id=14;
SELECT * FROM example  WHERE name="M1A7hAUlxB4c7Ok9aoRqm";
SELECT * FROM example  WHERE id=5;
INSERT INTO qyBPZ (id,name,pwd) VALUES (null, 'GzAXKjH6t7MCXrFyaIV2ouVCLIW', 'zTcgUuxXWyPdN4KVfHD');
INSERT INTO qyBPZ (id,name,pwd) VALUES (null, 'qx', '4dhCJbSL4sZhAtjeK');
INSERT INTO qyBPZ (id,name,pwd) VALUES (null, 'KS4KIEoMoYnv3zjh5M56s6K2roOy', '');
SELECT * FROM example  WHERE id=11;
SELECT * FROM example  WHERE name="varus";
INSERT INTO qyBPZ (id,name,pwd) VALUES (null, 'N8yT3axir8Mp4A73io7p9', 'Cc6en');
SELECT * FROM example  WHERE name="";
INSERT INTO qyBPZ (id,name,pwd) VALUES (null, '7cj3yOEj', 'k0sFX8RdZSOh61gl');
SELECT * FROM qyBPZ  WHERE id=7;
SELECT * FROM qyBPZ  WHERE id=4;
SELECT * FROM qyBPZ  WHERE id=6;
SELECT * FROM qyBPZ;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
