use db;
CREATE TABLE RbxaQ (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, '', '7eEwN49gh4dWuppimZgC0WOKjv');
SELECT * FROM example  WHERE name="cathy3333";
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, '7E', 'z6FVaqjHCULtdvykD9TZ');
SELECT * FROM example  WHERE name="yuhateme";
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, 'ATR15Re1CYMTE0WOJ5Ou', '9JTQCSfdx');
SELECT * FROM example  WHERE name="4hH";
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, 'bTyj73auHkQh16iikqepeKJtQ', 'lIYwrcau10tBYurNdspSAa1');
SELECT * FROM RbxaQ;
SELECT * FROM example  WHERE name="gaga";
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, '', 'Qe9axmmpaTZRidEDgT93');
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, '6omAexAoBsKi63', 'TA4PMtPpNWRPfTEc56goZAscB9C6h');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, 'YABnbKE30P87Hf9t', 'lHwmMJa2kzZ7jVF');
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, 'VQHgwdMlpN4FanfRiYI3z7l', 'wXcslQWTb3niDaS4jfqpGPH8lusiO');
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, 'ocWPo4irWrpsGasQzD6HKhWaQZx', 'kQmTEEYUbJz');
SELECT * FROM example  WHERE id=11;
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, 'QMpTR2KnZtoO', 'RIdaVyM3isbA');
INSERT INTO RbxaQ (id,name,pwd) VALUES (null, 'Q6kGu66m08WVGFhbhlLnhM5gfAt42', 'TmksXh');
SELECT * FROM example  WHERE id=3;
SELECT * FROM RbxaQ  WHERE name="8k4guTZU5dsZo";
SELECT * FROM RbxaQ  WHERE name="PRipqvAv7cCklmSk8WEsdixpan";
SELECT * FROM RbxaQ  WHERE name="H8biaFUpJNHpDAnCnqjgIbaB";
