use db;
CREATE TABLE OiWVT (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'qF5BkvYEd6Ccncc5h93DO', '7tbeZmnCMuD4gm7XL9ERNx13L');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'cAv0ZqjW53Ro3A4QHkYtsaJytxgy', 'fX3X17j6a10bZ');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, '7h', '1bKcDJiuic4NZ6So');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'twOPgafpXf6juxXlwl', 'TTsYCm8PnKsFVLc5kU');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'KW', 'f4BDy9f6MvoxiDenYY5tZaS7RvQzG');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'PutOPWoYFpcWO2qGdTYH', 'Zjali1GbCa0Xht');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'VoQ6K6zBZL', 'Mwyhirh05gzFwGWaIovhqA');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'z', '4H3L4JaG8dXNgs1fDTDwnYsMS2lv');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'vkVy4Bsfl2j', 'nn7fBZW7DGYL');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'zH4mhGv9ttkbm1M2dA', '2p4J64wODsWPDmN3Zs4jdd');
SELECT * FROM example  WHERE name="varus";
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'UX', 'XRIdusJxVTi6V0x');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'K7QcVxIjNMVA7eOIBtWo8pHW', 'CnIJ1JJJgpmhEl1yN1Q22BKVJ6');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'HDLgev899EjQdT6o', '26liTYMLqsJ4wRNTmqYF7qXG');
SELECT * FROM example  WHERE name="elephant";
SELECT * FROM example  WHERE id=3;
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'jcnais2VWBtXKW', 'aTdX');
SELECT * FROM example  WHERE name="hollywood36830";
INSERT INTO OiWVT (id,name,pwd) VALUES (null, '0yT', '37vNGdICTWXWfR9JsBOG1tzfgHgmo');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'J', 'RqweT4KjyReop');
INSERT INTO OiWVT (id,name,pwd) VALUES (null, 'OxB7DezbvSPl8qGWCVdrfWehBmE', 'V8GHAdhhoYKQ1');
SELECT * FROM OiWVT;
SELECT * FROM OiWVT  WHERE id=6;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM OiWVT  WHERE name="mr4pazGB4rMUjg8Isy9Ymet5D";
SELECT * FROM OiWVT  WHERE name="l13awNcVmuilpX";
