use db;
CREATE TABLE HbLhI (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="73GlQ1ygR";
INSERT INTO HbLhI (id,name,pwd) VALUES (null, 'aOHitXp0hpWreJ1t0aAsKeSQ6V', 'WG0AO7YRqG');
INSERT INTO HbLhI (id,name,pwd) VALUES (null, 'ji', 'riDGuyDYRgZIsUTGD8Tygxj');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE id=16;
INSERT INTO HbLhI (id,name,pwd) VALUES (null, 'Q2lK', 'UNJ');
INSERT INTO HbLhI (id,name,pwd) VALUES (null, 'J1peAmkd2TP', 'TIwSluiMbBB');
SELECT * FROM HbLhI;
SELECT * FROM example  WHERE name="faker";
SELECT * FROM example  WHERE name="google";
INSERT INTO HbLhI (id,name,pwd) VALUES (null, 'OUO9JVqDW1jIkEb73WY', 'ayrLanrPEYbVG71SdSHax');
SELECT * FROM example  WHERE id=19;
INSERT INTO HbLhI (id,name,pwd) VALUES (null, 'TTMFv62bbwGCP', 'V6oB5KGT4l2x1y');
SELECT * FROM example  WHERE id=12;
INSERT INTO HbLhI (id,name,pwd) VALUES (null, 'DXiA6KtM4PoQRmoDy', 'IihLoXMpjdOsRJvp');
SELECT * FROM HbLhI  WHERE name="yOGPzbaGJGmjbp";
SELECT * FROM HbLhI  WHERE id=0;
SELECT * FROM HbLhI  WHERE id=4;
SELECT * FROM HbLhI  WHERE name="W2IHnV39";
SELECT * FROM HbLhI  WHERE id=7;
SELECT * FROM HbLhI  WHERE name="ibTB9zJ5MEy6aeOYv6RfbCUyC";
SELECT * FROM HbLhI  WHERE id=1;
