use db;
CREATE TABLE ggvBJ (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="WT6kUHzuIPb7fDjFCy";
SELECT * FROM example  WHERE name="GG5K8O5YAHfWc6FdHvcWcZI";
INSERT INTO ggvBJ (id,name,pwd) VALUES (null, 'Py4rR', 'zn4SF');
SELECT * FROM example  WHERE name="gaga";
INSERT INTO ggvBJ (id,name,pwd) VALUES (null, 'NS7gCvxi2UJG07ALDaRrzJ3rMmxoN', 'tvyrRqsAhvND');
SELECT * FROM example  WHERE name="pEGqTiZPYK7QNf1uRSZG8Hlv38";
SELECT * FROM example  WHERE name="ufortable";
INSERT INTO ggvBJ (id,name,pwd) VALUES (null, 'hzNH33AWKuvuVgbBEx87n9', 'qZeuV');
INSERT INTO ggvBJ (id,name,pwd) VALUES (null, 'DhooD2c5K2xh14K', 'CJZhbjAAqTHIoXlOqLvp');
SELECT * FROM example  WHERE name="XY";
INSERT INTO ggvBJ (id,name,pwd) VALUES (null, 'WmjIWHJlzlipddzlo', 'A57mNWQb2EFoBbpy7Q726Wj');
SELECT * FROM example  WHERE name="zookeeper001";
SELECT * FROM example  WHERE name="friend";
SELECT * FROM ggvBJ  WHERE name="cDBbhIKQQG7nl";
SELECT * FROM ggvBJ;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM ggvBJ  WHERE name="0jUs14pgS6Q65BmHlwZ9Sqr6G";
SELECT * FROM ggvBJ  WHERE name="QQZgeks7EjSOhKDu";
