use db;
CREATE TABLE eDVtD (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="queenofthrone";
INSERT INTO eDVtD (id,name,pwd) VALUES (null, 'hC9GJXJifXownAS', 'rCw2GD9zjYRTlrba5');
INSERT INTO eDVtD (id,name,pwd) VALUES (null, '4tG5ZVl3zDmGHzDW', 'eneriGdEvIJ');
INSERT INTO eDVtD (id,name,pwd) VALUES (null, 'fU3XS0wUe', 'zQJJEBcysJb2F');
INSERT INTO eDVtD (id,name,pwd) VALUES (null, '2572mRTO72MX3p', 'zBI0VYbDEyoZ7l6MiMik6Q');
SELECT * FROM example  WHERE id=16;
INSERT INTO eDVtD (id,name,pwd) VALUES (null, '9V0wbNYEsqz0je1BrL', '33le6bANu6afdUshzEeYw8Gwwu');
INSERT INTO eDVtD (id,name,pwd) VALUES (null, 'YKZkjnaHWag34Q', 'y6NqHVGZKyot9te');
SELECT * FROM example  WHERE id=16;
SELECT * FROM example  WHERE name="cici1001";
INSERT INTO eDVtD (id,name,pwd) VALUES (null, 'LGVnHBY2z5EHbC', 'oQtcnDVIvjvNdrNtt7cI865VbM');
SELECT * FROM example  WHERE id=4;
SELECT * FROM example  WHERE name="WksayT";
INSERT INTO eDVtD (id,name,pwd) VALUES (null, 'ORSYi9xGsaSp1GH0dWMhOpVHIYc', 'Q5Qkc19kUZGQfahkr4');
SELECT * FROM example  WHERE name="bhHNHtJSIVgM5";
INSERT INTO eDVtD (id,name,pwd) VALUES (null, '', 'bzUJL9EBV62LkuFvPUSp');
INSERT INTO eDVtD (id,name,pwd) VALUES (null, 'Yw27P', 'FDi');
SELECT * FROM example  WHERE id=10;
SELECT * FROM example  WHERE name="duck233";
INSERT INTO eDVtD (id,name,pwd) VALUES (null, 'unKO6eiTsxwTd', 'eV1e51SGM03Ioqi');
INSERT INTO eDVtD (id,name,pwd) VALUES (null, '04nAr1zt4CPvwqZVvoOKHz9', 'FlYx');
INSERT INTO eDVtD (id,name,pwd) VALUES (null, 'VQv5ms', 'jqf9OwhWn7c07DJZIulLpvBDa');
SELECT * FROM example  WHERE name="test";
INSERT INTO eDVtD (id,name,pwd) VALUES (null, 'iVTBM4z3beb', 'ooKdZ5iMA');
SELECT * FROM eDVtD;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM eDVtD  WHERE name="y";
SELECT * FROM eDVtD  WHERE name="5ch7fh7WMr1";
SELECT * FROM eDVtD  WHERE id=3;
