use db;
CREATE TABLE eZeeN (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO eZeeN (id,name,pwd) VALUES (null, 'kig6HTkH599Ue9EN5ki', '3isHqBw');
SELECT * FROM example  WHERE name="oJ";
INSERT INTO eZeeN (id,name,pwd) VALUES (null, 'fvGt8m6NlsEWB6t2TkMshFK', 'J');
INSERT INTO eZeeN (id,name,pwd) VALUES (null, '1lLr20oqC43GB4crG', 'PmlBPkbrdSOm0a6v33Vmeoab');
SELECT * FROM example  WHERE name="EgxkrScekNRKmusa7d7jN";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE name="j0rm1QL2q27X1Egt";
SELECT * FROM example  WHERE name="spXp4tzeQiRbwE";
INSERT INTO eZeeN (id,name,pwd) VALUES (null, 'G3qSUtQaVOdZ8X0ArQQBs7Z4o', 'nEzH');
SELECT * FROM eZeeN;
INSERT INTO eZeeN (id,name,pwd) VALUES (null, 'dnFifCXjJMBJJSfLaB25G87', '8S4Lq');
SELECT * FROM example  WHERE id=15;
INSERT INTO eZeeN (id,name,pwd) VALUES (null, 'O', 'CK8I3Fi29WQ20ffxV4eGGr0Z13ECQ');
SELECT * FROM eZeeN  WHERE name="TdtMLJJIlgWLsnPe20aJ6vc4";
SELECT * FROM eZeeN  WHERE id=0;
SELECT * FROM eZeeN  WHERE name="u1zE8n9tqYfjIQJOu0";
SELECT * FROM eZeeN  WHERE name="Q7zdFcCoaNnGtd";
SELECT * FROM eZeeN  WHERE name="p8TalcS";
