use db;
CREATE TABLE glIgO (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO glIgO (id,name,pwd) VALUES (null, '0PcspDQmNF', 'TqWhVJefiVweHdDdL2YSDgjnn2');
SELECT * FROM example  WHERE id=0;
SELECT * FROM example  WHERE id=11;
INSERT INTO glIgO (id,name,pwd) VALUES (null, 'mvYHFuCDKV1NKrB2ktNWYrq7v', 'StJLSryLM9CkoQbPCm1eelBQO');
SELECT * FROM example  WHERE id=10;
INSERT INTO glIgO (id,name,pwd) VALUES (null, 'VaUQGEtMlPfV9RoQ', '2Y2uRrPsLpYON0BXHJ5Dz1Xt');
SELECT * FROM example  WHERE name="queenofthrone";
SELECT * FROM example  WHERE id=7;
SELECT * FROM example  WHERE name="duck233";
INSERT INTO glIgO (id,name,pwd) VALUES (null, 'NsjebpVKTiF', 'cOozf2vCC2noeQyx');
SELECT * FROM example  WHERE name="cathy3333";
SELECT * FROM glIgO  WHERE id=2;
SELECT * FROM glIgO  WHERE name="5J99OX38VO1xh";
SELECT * FROM glIgO;
SELECT * FROM glIgO  WHERE id=1;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM glIgO  WHERE id=1;
SELECT * FROM glIgO  WHERE id=4;
SELECT * FROM glIgO  WHERE name="dWUqI8zqLHcGd7TxvQ";
