use db;
CREATE TABLE bTJPE (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO bTJPE (id,name,pwd) VALUES (null, 'dUlFnhHkjp3vvXSuV6kmKj', 'ZUM6JaeCi6uoRS6O');
SELECT * FROM bTJPE;
INSERT INTO bTJPE (id,name,pwd) VALUES (null, 'OYzjpYRo8K7wi1keZGqdWXI', '');
INSERT INTO bTJPE (id,name,pwd) VALUES (null, '5VEXscyK8yAbu83', 'jBbJCW5A8pZ00h');
INSERT INTO bTJPE (id,name,pwd) VALUES (null, 'loRjSMy1qvHJYTBYNpQjPfng', '241HwvaXDPwgCtXQG0s5Zj3');
INSERT INTO bTJPE (id,name,pwd) VALUES (null, 'Yj', 'KnQ1in');
SELECT * FROM example  WHERE id=12;
INSERT INTO bTJPE (id,name,pwd) VALUES (null, '5XY0jj8jaM0AB', '1HiWW6DTGmTmDInQNfM');
SELECT * FROM example  WHERE id=19;
INSERT INTO bTJPE (id,name,pwd) VALUES (null, 'K1TuI4aR8rlCGauQEdksY8p', 'QjJh');
SELECT * FROM example  WHERE name="mickeymouse";
INSERT INTO bTJPE (id,name,pwd) VALUES (null, 'fzwRMZTCWTj2zssvQAhN', 'zz9Hh');
INSERT INTO bTJPE (id,name,pwd) VALUES (null, 'yDtQWqzgzW1vO4T4sagH6', 'fCiU47t48RXNFUU');
SELECT * FROM example  WHERE id=1;
SELECT * FROM example  WHERE id=19;
INSERT INTO bTJPE (id,name,pwd) VALUES (null, 'GpR2nyXt0JIadTzJdA43Kq5aoY5', 'B6uJqpSfOWAJN9R8DaNSvcU7fKUs');
INSERT INTO bTJPE (id,name,pwd) VALUES (null, '1MLvxsnJhoR5RS4aDhZTeh6fal', 'DSHUDLLpyYcotMh6DQ0r07cHKhUUO');
INSERT INTO bTJPE (id,name,pwd) VALUES (null, 'Ci4j', 'bvDHE06rqnmYOYYb');
SELECT * FROM example  WHERE name="lemonpie";
SELECT * FROM example  WHERE name="mickeymouse";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
INSERT INTO bTJPE (id,name,pwd) VALUES (null, 'EiU5tJNGwZX4R2Pe', 'qp1rLlDeN5tF6X6gCzc3txIx');
SELECT * FROM bTJPE  WHERE name="r0tNWX8HDT4chh4aZnRragVSb";
SELECT * FROM bTJPE  WHERE name="rm5XkjQC3sy08";
SELECT * FROM bTJPE  WHERE name="0kd1Hwj272Jy0Lu";
SELECT * FROM bTJPE  WHERE name="ANFyh9Ov26zp";
