use db;
CREATE TABLE rRQnr (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO rRQnr (id,name,pwd) VALUES (null, '09zX', 'U7qozGL7Tn5Z9nRfah7EAcc78uAC');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'cws46', 'OxsQurMHq');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'iGbbwl7BvnzSGNu3RLDaExa9', 'TSieXczS23vemC13ngBk2');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, '4wGpttyqF66hr95jpNDpqrw5Zv', 'sDJgfg9N6q3qRvjnjeMeDKKVlv');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'qO7BpXIVPEijQ5j8bEFqhPcVTwSjl', 'zedd94q0JmEWf25');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'J9UdBtZyddRCNQRkr3X1jmN1', 'W27GdhjTMA');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, '6QHyJ33bIzKFvtHKAEYiUjcVs', '5C4o2qPGcvXOMf96ah');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'itRAbOXcFlbI3A0yDmnNDNRl52p', 'LGWAaB0d6MO3');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'QIx8vM3EtjYaMVpRj', 'Xyi1ph0h');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'jKrwgMoagY1Tsj44Keo', 'RyRoYDkREnKz3aZnFkqzux9');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'pPRv0a4LKBkjLa9nXdezbTYQI', 'z7o');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'pjTMYonUaUyLwRNE', 'jNAZ4RTToTsJ');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'EeJlyF7C7', '');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'MV', '8W8gxUPCxxtA');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'Nj41OV', '1Ap0EUDKAF0gRu4CTGon19i');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'm9v94J', 'mEfadlnKqkVY4i3vLM3KSACAzz');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, '2XH1Bi2evPmJBsxpd7uLq', '1jn1SKydh0gdF1');
INSERT INTO rRQnr (id,name,pwd) VALUES (null, 'O6qshInDxnDwVSeCRVUbbcDq', 'EFjq');
SELECT * FROM rRQnr  WHERE id=11;
SELECT * FROM rRQnr;
SELECT * FROM rRQnr  WHERE id=13;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
