use db;
CREATE TABLE dAvlm (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO dAvlm (id,name,pwd) VALUES (null, 'wcvl9hQyQ0BFF1rb3T', 'Q8Ia6uDPEUTDeg9f9btPCVisobp');
INSERT INTO dAvlm (id,name,pwd) VALUES (null, 'FnXEhItZMMIUOTYr7X', 'JYPVTuw8iTARCJHCn4sFnDP3WRrcC');
INSERT INTO dAvlm (id,name,pwd) VALUES (null, 'q9K4qeY63YlsqaQU7gfo6YCLHEI', 'h6y6Z9o');
INSERT INTO dAvlm (id,name,pwd) VALUES (null, 'G1RvOe4z4g47XSL2Lk9', 'DYf9HWASozFupiFmTgL8q90yXH');
INSERT INTO dAvlm (id,name,pwd) VALUES (null, 't8U70507u7axSvFjri8vWoy', 'Ad3z60hyq7l4zQHQ8lKdsTjmF');
SELECT * FROM example  WHERE name="wickedbanana";
INSERT INTO dAvlm (id,name,pwd) VALUES (null, 'XAngDzYPNKLCRyFXAjmg4nbsFb5T', 'Gzd7r2SFkLh9v9Ah4L');
INSERT INTO dAvlm (id,name,pwd) VALUES (null, 'd2Sm9nfcWFwuIwIDNDFO', 'SW');
INSERT INTO dAvlm (id,name,pwd) VALUES (null, 'Jv7datpFBV6ziYtUeHaZ2hV10', 'wdG0RX4AWlF4qSH9isfcxOIpb');
INSERT INTO dAvlm (id,name,pwd) VALUES (null, 'cmtumnJv6', 'rexlhi7bqV4q3S6ssODRH7');
SELECT * FROM example  WHERE name="euro";
SELECT * FROM example  WHERE name="rightnow2019";
SELECT * FROM example  WHERE name="gaga";
INSERT INTO dAvlm (id,name,pwd) VALUES (null, 'CuGCl9i', 'k24jrKTIZHiScPbgjFfFAz6ZIo');
SELECT * FROM dAvlm;
SELECT * FROM dAvlm  WHERE name="uC2na";
SELECT * FROM dAvlm  WHERE name="c5";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM dAvlm  WHERE id=2;
SELECT * FROM dAvlm  WHERE id=10;
