use db;
CREATE TABLE XAIKe (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE id=7;
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'U', 'zbv');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'Djy7p', 'OvqDSXgHS3KA4XDbLQ5Ig');
SELECT * FROM example  WHERE id=11;
SELECT * FROM example  WHERE name="notebook";
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'bZjA2OxE3ulUVttgkyp', 'K0TskYuKcR1JsHK9HAXsxt8Yy');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'UlNmtZ', 'jzDSWgqNN');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 't40k3M1Bkvq', 'XJZzV4GQxiqSyh388RJ');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'InzapBAZUX91GfjGZr', 'HXkQXLaaw1HY');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'RfrFQ38gLlRq', '8BQGEU94ZqvBXFeoTBd');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, '6NAcri', 'Kz2ksmuEkqFQ5592L61');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'WHvGMev72UaLaaXwuLwnq', 'SfXlDF0VztrOT8l7LlLmiwg9WZ');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'F0', 'aa');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'FcOGx', 'G9XYXmMtsGX9ep8JyE');
SELECT * FROM example  WHERE name="singular";
SELECT * FROM example  WHERE name="killerleon";
INSERT INTO XAIKe (id,name,pwd) VALUES (null, '', '1UlQPITMIZmMY8fNGEVdlCHDZn');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'ju4If3NuG', 'i');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'KIOq8rOsL9', 'xjxTFZH');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, '2oJjMnnfgVpu', 'Au');
INSERT INTO XAIKe (id,name,pwd) VALUES (null, 'ONaq', 'oGMzXj');
SELECT * FROM XAIKe  WHERE id=14;
SELECT * FROM XAIKe  WHERE name="tARfmo4U";
SELECT * FROM XAIKe  WHERE name="Ea6Td7xkllvy240YXn";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM XAIKe  WHERE id=11;
SELECT * FROM XAIKe  WHERE id=2;
SELECT * FROM XAIKe;
SELECT * FROM XAIKe  WHERE name="O4xtrKRoEZyF3KlBcjvPr2gA0Ad8";
SELECT * FROM XAIKe  WHERE id=11;
