use db;
CREATE TABLE GdUHH (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM example  WHERE name="ZUz6xumKcSrmvvHJacOPkNl83";
INSERT INTO GdUHH (id,name,pwd) VALUES (null, '1HjP4gJNlWsr', 'q8dPWCIREA9gYaDiIO8Yd');
INSERT INTO GdUHH (id,name,pwd) VALUES (null, '9W7skqVBmDTtWrKs9', 'dfFufWTYeEmaWeyA8yTdCvLLufh0');
INSERT INTO GdUHH (id,name,pwd) VALUES (null, '46mlo', 'zqvWdFSqlVffmzdWctKjObftDQL');
INSERT INTO GdUHH (id,name,pwd) VALUES (null, '', 'oD9MneBC66xYjw0XdXtaHr89Zss');
SELECT * FROM example  WHERE id=14;
INSERT INTO GdUHH (id,name,pwd) VALUES (null, 'DRSbilGc8XujrwuN3THlUeC0', 'QO9m9m');
INSERT INTO GdUHH (id,name,pwd) VALUES (null, 'wWj9OlYB7XCn3G', 'zLJ5rIPE0FO');
INSERT INTO GdUHH (id,name,pwd) VALUES (null, '69Bxa', '3H');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE name="xeoncpu";
INSERT INTO GdUHH (id,name,pwd) VALUES (null, '46zCDhQOqJrmpK6GAzas', 'xlqx1EtHaIEoP30DGjkmc');
SELECT * FROM example  WHERE id=8;
INSERT INTO GdUHH (id,name,pwd) VALUES (null, '3I2wh7mw5shiorpi', 'va');
SELECT * FROM example  WHERE id=11;
SELECT * FROM example  WHERE name="ufortable";
INSERT INTO GdUHH (id,name,pwd) VALUES (null, 'ABpoQBu7Xwk7', 'cCoU');
SELECT * FROM example  WHERE name="qmF59I1YfsvhvX8";
INSERT INTO GdUHH (id,name,pwd) VALUES (null, 'on', 'iEyYr1gGTRls9');
INSERT INTO GdUHH (id,name,pwd) VALUES (null, 'aamezxI4yekvn4', '7F1');
SELECT * FROM GdUHH;
SELECT * FROM GdUHH  WHERE id=10;
SELECT * FROM GdUHH  WHERE name="RX9fblg0pGe0p2G";
SELECT * FROM GdUHH  WHERE name="XOtLPP9c3okdSDz";
SELECT * FROM GdUHH  WHERE name="FinWsx1STpUyHrn9oyCUk";
SELECT * FROM GdUHH  WHERE name="neTrMTwBGAQNt";
