use db;
CREATE TABLE Rixii (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'QeD', 'xXbjI2Bx8b');
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'j45Vj9aUy', 'w0VtBaZHxpZIgSICj1ejDJWWWxfb');
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'CSLDwRWqRqHL1VsnoXy7F78oH5hZ', 'Of6Pesjg4wxLlqRw');
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'pA7SfL5', 'p9QtR7ulSyrS');
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'n1hPP', 'm0j6P93Sty2r');
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'f', 'CvQvlCLuHDs');
INSERT INTO Rixii (id,name,pwd) VALUES (null, '3v', 'CpYEkUN37r67');
INSERT INTO Rixii (id,name,pwd) VALUES (null, '6OSdDu5n3J', 'Ow');
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'n8lz', '1GYUqrRgQSkq8qtsDXagyLif9s1O');
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'PRMgtNkTMATguO12lgd', 'iFpmXlmT7UXTrva0yyocRpE');
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'lPMQUYp5uF0Q', '7MMZyHyfk');
SELECT * FROM example  WHERE name="hollywood36830";
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'WtkL8', 'nbcYLHkgk4psQVOOGMcbuWC');
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'P4Z0vZ3nyz1VzEgHFNcvZgTk6vI', 'g65Ml8ITx7KcrQ7Yi07qKLH');
INSERT INTO Rixii (id,name,pwd) VALUES (null, 'CuatqhZXIuw4mGP7A9Ag0TP', 'vel3');
INSERT INTO Rixii (id,name,pwd) VALUES (null, '', '3InR9pSbf5fW');
SELECT * FROM Rixii  WHERE id=9;
SELECT * FROM Rixii  WHERE name="INw58LJU6rdUbJBVl8rALo5cE";
SELECT * FROM Rixii  WHERE id=13;
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM Rixii  WHERE name="MLS8bP1EakzHcZa";
SELECT * FROM Rixii;
SELECT * FROM Rixii  WHERE id=7;
SELECT * FROM Rixii  WHERE id=2;
