use db;
CREATE TABLE ApdlC (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
INSERT INTO ApdlC (id,name,pwd) VALUES (null, 'CoiVNPUUMI5', '0349EJ1cYIHkLBLx');
INSERT INTO ApdlC (id,name,pwd) VALUES (null, '22cwTjJlrD51hFeuyAa71XP9knoam', '0fi6hPBfNBFeBabUyy8DxGjpy584');
SELECT * FROM example  WHERE name="notebook";
INSERT INTO ApdlC (id,name,pwd) VALUES (null, 'EmHrnt0UxmIiSuYhFLsdwRAXXB', '84');
SELECT * FROM example  WHERE id=17;
INSERT INTO ApdlC (id,name,pwd) VALUES (null, 'gNDlGQhvOFNl', 'FIH2F7BI295q4HPHMB6PIm');
INSERT INTO ApdlC (id,name,pwd) VALUES (null, '2EjmAJRqMuQ24zdV', 'TKd7dg0wRHaYBitQr5mMTwrJ04lOB');
INSERT INTO ApdlC (id,name,pwd) VALUES (null, 'P', 'YnDuDVra2FZgjGWn7ncI');
INSERT INTO ApdlC (id,name,pwd) VALUES (null, 'y', 'Hr7GmzbomQNyDY1H9');
SELECT * FROM example  WHERE id=15;
INSERT INTO ApdlC (id,name,pwd) VALUES (null, 'GoOHtSF7na3eO3xFRUeilgh', 'IQy2SOPDT4');
INSERT INTO ApdlC (id,name,pwd) VALUES (null, 'oWNK07L', 'TOqKjJ8k6mN4aR7hZHGu');
SELECT * FROM example  WHERE name="google";
INSERT INTO ApdlC (id,name,pwd) VALUES (null, 'XvYGshqfbQUKzoHeuvOQoVzNaq', 'G8MKtDukjNlc');
SELECT * FROM example  WHERE id=6;
INSERT INTO ApdlC (id,name,pwd) VALUES (null, 'naTbCvk66bN', '');
SELECT * FROM example  WHERE id=0;
INSERT INTO ApdlC (id,name,pwd) VALUES (null, 'DTMLTzwd', 'AKwvD7XaVImEycfk');
SELECT * FROM ApdlC  WHERE id=7;
SELECT * FROM ApdlC  WHERE name="cB0K";
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM ApdlC  WHERE id=2;
SELECT * FROM ApdlC;
SELECT * FROM ApdlC  WHERE id=11;
SELECT * FROM ApdlC  WHERE name="rWx65I1IpWmd8C3rb0JF";
