use db;
CREATE TABLE gPWFc (id smallint unsigned not null auto_increment, name varchar(32) not null, pwd varchar(32) not null, constraint pk_example primary key (id));
SELECT * FROM gPWFc;
INSERT INTO gPWFc (id,name,pwd) VALUES (null, 'qV', 'TNgZDrq9cqMtIisuO2QtqAe5U');
SELECT table_name FROM information_schema.tables WHERE table_schema="db";
SELECT * FROM example  WHERE id=7;
SELECT * FROM example  WHERE id=17;
SELECT * FROM example  WHERE name="hollywood36830";
SELECT * FROM example  WHERE name="euro";
SELECT * FROM example  WHERE name="GKdvr2fFR171ECZ9W";
