use db;
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
DELETE FROM example WHERE name="cathy3333";
DELETE FROM example WHERE name="NkVUTcWHKWsUi8";
INSERT INTO example (id,name,pwd) VALUES (null, 'cathy3333', 'ZwyHYqFojhhX4IFsV7taTX6UL');
